### ISSUE TITLE
mpirun problem with domain2

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#208] opened 2016-04-19 14:15 UTC
I am now getting an error when run the domain2 version of python that is associated with the mpi command

mpirun -np 4 py80_dom2 reflect
## The error looks like this:

mpirun has exited due to process rank 1 with PID 4017 on
node clsockeyev1 exiting improperly. There are three reasons this could occur:
1. this process did not call "init" before exiting, but others in
   the job did. This can cause a job to hang indefinitely while it waits
   for all processes to call "init". By rule, if one process calls "init",
   then ALL processes must call "init" prior to termination.
2. this process called "init", but exited without calling "finalize".
   By rule, all processes that call "init" MUST call "finalize" prior to
   exiting or it will be considered an "abnormal termination"
3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
   orte_create_session_dirs is set to false. In this case, the run-time cannot
   detect that the abort call was an abnormal termination. Hence, the only
   error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command line.

My suspicion is that this error is due to something associated with the fact that I have created new spectra in the SpecPtr array.

I've put the problem reflect.pf in the bug_pf_files folder on DropBox.  Help would be appreciated @jhmatthews @Higginbottom

**Comment by kslong** [comment] 2016-04-20 15:31
I have run this model now in single string, and it fails there because it gets too many errors associated with a photon not being in the wind. That is the problem arises due to bug #154

**Comment by jhmatthews** [comment] 2016-05-02 17:43
Knox I'm closing this one. The above issue is the error message MPI reports when the code crashes for other reasons.

**Closed as completed by jhmatthews** 2016-05-02 17:43 UTC

**Comment by kslong** [comment] 2016-05-02 19:16
I understand that this is the result of another problem, but the question is what was causing the program to actually fail.  Has the problem been fixed or not?    If not, then it is inappropriate to close it.

**Comment by jhmatthews** [comment] 2016-05-02 21:18
Right, but I unless I've missed something the root cause is flagged elsewhere under the reopened issue #154

**Comment by kslong** [comment] 2016-05-02 22:16
I do not think you are correct James, but could be mistaken.  I am in the process of running the same .pf file which caused the original problem, and will check.

I also believe that in dom2,e #154 is fixed in dom2, though others should confirm this.  dom2 now uses variable sized DFUDGE once the photon is in a wind cell.Thish reduces the number of times that the photon gets out of a cell in the wind.

**Comment by kslong** [comment] 2016-05-03 17:14
OK, @jhmatthews  you are correct this problem has gone away.  I was wrong. In running the reflect.pf file referenced above, I do see the error, but it is due to the fact that in a coronal model extracting at inclination 0 results in the velecity being 0 on both sides of the cell.  This happens a million times and the program quits both in parallel and single processor mode.   The problem disappears if you set the extraction direction to 1 degree. So there is no mpirun problem.  (We still need to decide whether we want to keep trapping this issue or not.  I think for now the answer is yes, keep tracking it; it nudges us in the direction of solving the issue of what to do when the Sobolev approximation does not apply.)
