### ISSUE TITLE
Excessive angle dependent continuum flux observed with optically thin wind in extract mode

### ISSUE THREAD

**Issue by mandyhewitt** [sirocco-rt/sirocco#635] opened 2019-10-31 17:40 UTC
On dev branch, at inclination angles greater than 45 degrees (and most prominent at angles very close to 90 degrees) an excessive continuum flux is observed when running various different optically thin python models. It appears as if the multiplier effect for flux is higher if the gap between the wind and central source is large, and the multiplier is reduced as the central source radius approaches the wind. This bug occurs with EXTRACT option... Live or Die does not show this issue.

This was seen in both standard_sn_kurucz and standard80 atomic data files, with 1d_sn, homologous and a simple hydro model. The models were run on a single processor and no difference is observed in using multiple processors. Also, no major difference is clear
by including a disc.

Here are some plots showing the contrasting effect:

Firstly a set of spectra using Live or die option - without varying the wind position (inner radius 1.2e15 cm) the central source radius was increased. These spectra are as expected. 

![homwinderrlod](https://user-images.githubusercontent.com/32335653/67966585-096d5000-fbfc-11e9-8b74-b45f9e6312b3.png)

The top panel is a 0.8Msol star with an optically thin homologous disk wind **touching** the central source. In the second panel a 7 solar mass star (radius 7e8cm) and in the bottom panel a B0 type (18 solar mass) central source (radius 5.15e11 cm). The wind parameters were kept constant and the wind is optically thin - so no scattering occurs. The wind has a very thin radius.

Now, the same systems changing only the photon extraction method to extract (instead of live or die):

![homwinderrext](https://user-images.githubusercontent.com/32335653/67967762-18ed9880-fbfe-11e9-90eb-ff9d22d5dc30.png)

Zooming in shows the effect of angle dependence in extract mode:

![Screenshot 2019-10-31 at 17 05 09](https://user-images.githubusercontent.com/32335653/67969181-a5995600-fc00-11e9-92cf-c412456509e7.png)

In the first panel above, with no gap between central source and wind, spectra seen at each observer angle tracks the created flux (as expected). However, as the stellar radius is decreased (i.e. gap increased between central source and wind), the continuum flux **increases with angle** as we approach the equator. NB Purple represents 89.9 degrees.

Here are the parameter files:

[7MsolBigGapLOD.txt](https://github.com/agnwinds/python/files/3795015/7MsolBigGapLOD.txt)
[NoGapLOD.txt](https://github.com/agnwinds/python/files/3795025/NoGapLOD.txt)
[18MsolLOD.txt](https://github.com/agnwinds/python/files/3795030/18MsolLOD.txt)
[NoGapEXT.txt](https://github.com/agnwinds/python/files/3795048/NoGapEXT.txt)
[7MsolBigGapEXT.txt](https://github.com/agnwinds/python/files/3795056/7MsolBigGapEXT.txt)
[18MsolEXT.txt](https://github.com/agnwinds/python/files/3795061/18MsolEXT.txt)

**Comment by lazygun37** [comment] 2019-10-31 17:57
Sorry - is this for a spherical continn source or for a disk or both?

Sent from my iPhone

On 31 Oct 2019, at 17:40, Mandy Hewitt <notifications@github.com> wrote:

﻿

On dev branch, at inclination angles greater than 45 degrees (and most prominent at angles very close to 90 degrees) an excessive continuum flux is observed when running various different optically thin python models. It appears as if the multiplier effect for flux is higher if the gap between the wind and central source is large, and the multiplier is reduced as the central source radius approaches the wind. This bug occurs with EXTRACT option... Live or Die does not show this issue.

This was seen in both standard_sn_kurucz and standard80 atomic data files, with 1d_sn, homologous and a simple hydro model. The models were run on a single processor and no difference is observed in using multiple processors. Also, no major difference is clear
by including a disc.

Here are some plots showing the contrasting effect:

Firstly a set of spectra using Live or die option - without varying the wind position (inner radius 1.2e15 cm) the central source radius was increased. These spectra are as expected.

[homwinderrlod]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32335653%2F67966585-096d5000-fbfc-11e9-8b74-b45f9e6312b3.png&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=3GCR31eGHPKE71c8jzuwtrT%2BrshRi6nPTxf5iWS3xRQ%3D&reserved=0>

The top panel is a 0.8Msol star with an optically thin homologous disk wind touching the central source. In the second panel a 7 solar mass star (radius 7e8cm) and in the bottom panel a B0 type (18 solar mass) central source (radius 5.15e11 cm). The wind parameters were kept constant and the wind is optically thin - so no scattering occurs. The wind has a very thin radius.

Now, the same systems changing only the photon extraction method to extract (instead of live or die):

[homwinderrext]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32335653%2F67967762-18ed9880-fbfe-11e9-90eb-ff9d22d5dc30.png&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=B%2B5kn9iE6%2Bov9sFer4q62Z0NvhIJga0e1RXxB3ir610%3D&reserved=0>

Zooming in shows the effect of angle dependence in extract mode:

[Screenshot 2019-10-31 at 17 05 09]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32335653%2F67969181-a5995600-fc00-11e9-92cf-c412456509e7.png&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=f8V%2FFdUV0oO8LJfmVmNF5O0TDS%2FzA%2BpNe3Ln70DHf1o%3D&reserved=0>

In the first panel above, with no gap between central source and wind, spectra seen at each observer angle tracks the created flux (as expected). However, as the stellar radius is increased, the continuum flux increases with angle as we approach the equator. NB Purple represents 89.9 degrees.

Here are the parameter files:

7MsolBigGapLOD.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagnwinds%2Fpython%2Ffiles%2F3795015%2F7MsolBigGapLOD.txt&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=GrrWh6lpI5kGkoUOHJS%2BF0GxkI7gwBgd57R2e9RtLe0%3D&reserved=0>
NoGapLOD.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagnwinds%2Fpython%2Ffiles%2F3795025%2FNoGapLOD.txt&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=bZt1%2FvAe4%2BPxqRo1PtY6kO5TMfto6bzwJfA5jIIFsE4%3D&reserved=0>
18MsolLOD.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagnwinds%2Fpython%2Ffiles%2F3795030%2F18MsolLOD.txt&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=EDkFIonqT2oEKQ5V3ow3xzXvX1fjG8lvVJCFz1F%2F90w%3D&reserved=0>
NoGapEXT.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagnwinds%2Fpython%2Ffiles%2F3795048%2FNoGapEXT.txt&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=eeWvOFws3ZoKIystaXHFPd22NhuGKRLzwHnmEkTQ84o%3D&reserved=0>
7MsolBigGapEXT.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagnwinds%2Fpython%2Ffiles%2F3795056%2F7MsolBigGapEXT.txt&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=nr93Gf4MdFFNDV6NYGpbXH6wf%2BathzXrAemhqPh5aN4%3D&reserved=0>
18MsolEXT.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagnwinds%2Fpython%2Ffiles%2F3795061%2F18MsolEXT.txt&data=01%7C01%7CC.Knigge%40soton.ac.uk%7C1df31abfa09a4d1ac0bb08d75e295cb6%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=Atbgf2vQ9HTTqPtb%2FJjQkHMRkLo3G6djnsUom5N2X2I%3D&reserved=0>

**Comment by saultyevil** [comment] 2019-10-31 19:13
When you say that no difference is observed when using multiple processors, does this mean that there is or isn't excessive flux for multiprocessor mode?

**Comment by mandyhewitt** [comment] 2019-11-01 12:42
@lazygun37 This is for a spherical central source and no disk. When I turned on a disk in the parameter file, it did not fix the issue of excessive flux at high observer angles. 

@saultyevil Regarding mpi on or not, initially I ran the code over 4 processors and that was where I saw the issue of higher flux at angles over 45 degrees.  I then ran the model without mpi and the excessive flux was still observed. i.e using mpi or not doesn't seem to change the behaviour and excessive flux is still seen.

**Comment by lazygun37** [comment] 2019-11-01 13:08
Could you check if the problem exists when the continuum is only a disk, I.e no photons from the central source?

Sent from my iPhone

On 1 Nov 2019, at 12:42, Mandy Hewitt <notifications@github.com> wrote:

﻿

@lazygun37<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flazygun37&data=01%7C01%7CC.Knigge%40soton.ac.uk%7Ca126d24c0e4f4264fea908d75ec8f304%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=kNmMbNxVFm63WmNX%2BQNUya2UlwkiQBrsrB5JR3CESE8%3D&reserved=0> This is for a spherical central source and no disk. When I turned on a disk in the parameter file, it did not fix the issue of excessive flux at high observer angles.

@saultyevil<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsaultyevil&data=01%7C01%7CC.Knigge%40soton.ac.uk%7Ca126d24c0e4f4264fea908d75ec8f304%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=qHI%2Bu8EsyE3tfZhPtvWTrXS3mp7xUZCi%2BpdxGlkyJpM%3D&reserved=0> Regarding mpi on or not, initially I ran the code over 4 processors and that was where I saw the issue of higher flux at angles over 45 degrees. I then ran the model without mpi and the excessive flux was still observed. i.e using mpi or not doesn't seem to change the behaviour and excessive flux is still seen.

**Comment by mandyhewitt** [comment] 2019-11-01 13:28
@lazygun37  will try that now - thanks for the suggestion.

**Comment by kslong** [comment] 2019-11-02 21:01
I have verified this is a problem for the pf file labelled 7MsolBigGapEXT.  I have also verified that we get the same results from a version of python dated in May, so this is not an issue that is very recent.

Note that in this model, there appears to be considerable interaction with the wind, as indicated in this plot of the total spectrum (produced by the latest version of run_check)

![image](https://user-images.githubusercontent.com/2530901/68076970-e1abf280-fd89-11e9-8678-594ae57ae2d0.png)

Higher inclination angles appear to produce systematically more flux

![image](https://user-images.githubusercontent.com/2530901/68076980-0011ee00-fd8a-11e9-9215-60269671a791.png)

I have also verified that if one runs in live or die mode, one does not see this effect.  

If one looks at the statistics of what is happening to photons in extract mode, it appears that for whatever reason photons are being lost to the central object

```
Inwind   Scat    Esc     Star    >nscat    err    Absorb   Disk    sec    Adiab(matom)
       0       0 1198560       0       0       0       0       0       0       0
       0       0 1198560       0       0       0       0       0       0       0
       0       0 1198560       0       0       0       0       0       0       0
       0       0       0       0       0       0       0       0       0       0
       0       0       0       0       0       0       0       0       0       0
       0       0       0       0       0       0       0       0       0       0
       0       0       0       0       0       0       0       0       0       0
       0       0  600717  598563       0       0     720       0       0       0
       0       0  666410  532789       0       0     801       0       0       0
       0       0  786294  412768       0       0     938       0       0       0
       0       0  899347  299585       0       0    1068       0       0       0
       0       0 1012702  186076       0       0    1222       0       0       0
       0       0 1197882     679       0       0    1439       0       0       0
```

and that, weirdly fewer of them are being lost at high inclination than at low inclination.  If there is no scattering in the wind, then we expect exactly half of the photons to be escape and half to hit the star.  That is close to what happens near 0 degrees, but almost all of them are escaping at 90d. 

Note that model altogether is odd, in that it appears  that ion fractions are not being calculated properly as well.  Here are the values for H.  (one gets the same answers with windsave2table and py_wind.  I am fairl suspicions that this has something to do with the ionization calculation, and possibly with things associated with the maximum change in density from ion to ion.

```
       r    i inwind      i01      i02 
1.20e+15    0     -1 0.00e+00 0.00e+00 
1.20e+15    1      0 1.50e+68 1.15e+62 
1.20e+15    2      0 1.50e+68 1.05e+62 
1.20e+15    3      0 1.50e+68 9.77e+61 
1.20e+15    4      0 1.50e+68 8.68e+61 
1.20e+15    5      0 1.50e+68 7.67e+61 
1.20e+15    6      0 1.50e+68 6.95e+61 
1.20e+15    7      0 1.50e+68 6.32e+61 
1.20e+15    8      0 1.50e+68 5.86e+61 
1.20e+15    9      0 1.50e+68 5.40e+61 
1.20e+15   10      0 1.50e+68 5.08e+61 
1.20e+15   11      0 1.50e+68 4.75e+61 
1.20e+15   12      0 1.50e+68 4.61e+61 
1.20e+15   13      0 1.50e+68 4.42e+61 
1.20e+15   14      0 1.50e+68 4.14e+61 
1.20e+15   15      0 1.50e+68 4.18e+61 
1.20e+15   16      0 1.50e+68 4.10e+61 
1.20e+15   17      0 1.50e+68 4.04e+61 
1.20e+15   18      0 1.50e+68 3.99e+61 
1.20e+15   19      0 1.50e+68 3.96e+61 
1.20e+15   20      0 1.50e+68 3.93e+61 
1.20e+15   21      0 1.50e+68 3.91e+61 
1.20e+15   22      0 1.50e+68 3.89e+61 
1.20e+15   23      0 1.50e+68 3.88e+61 
1.20e+15   24      0 1.50e+68 3.87e+61 
1.20e+15   25      0 1.50e+68 3.86e+61 
1.20e+15   26      0 1.50e+68 3.85e+61 
1.20e+15   27      0 1.50e+68 3.84e+61 
1.20e+15   28     -1 0.00e+00 0.00e+00 
1.20e+15   29     -1 0.00e+00 0.00e+00 
```

I am not sure if all these problems are related, or if there are several independent problems

**Comment by kslong** [comment] 2019-11-02 22:56
As noted above, the model that I first test of Mandy's is odd, and it looks like abundances are either not being calculated properly, probably because of a combination of factors.  We should understand that, but the problem with inclination angles appears to be independent of this, because one can create the problem with simple variants of our regression test.  

There is no problem with this version of star.pf which has the wind beginning at the stellar radius:
[star.pf.txt](https://github.com/agnwinds/python/files/3801029/star.pf.txt)

However, there is a serious problem with star2.pf which has the wind begin at a significant distance from the stellar radius

[star2.pf.txt](https://github.com/agnwinds/python/files/3801031/star2.pf.txt)

I suggest we focus on this example, since it is not extreme in other respects.

**Comment by kslong** [comment] 2019-11-03 20:20
Ok, I understand what is happening.  
- In our example all of the photons are being created on the star surface and (with low enough density in the wind) there are no interactions or emission from the wind
- When we extract a photon we invoke translate_in_wind and though it ds_to_wind.  This tries to translate from wherever you are to a wind cell, but it stops at the disk plane.  (If you have a photon that is on the -z hemisphre of the star, and extract at 0 inclination, the photon gets stopped at the z=0 plane; if on the other hand you extract at 90, e.g in the -z direction, the photon goes all the way to the wind.  At lesser angles it get stopped at the disk plane but a a distance that is typically a long way from the star.
- To check whether a photon hit the star, we really only check it's current position and see if is inside or outside the star (not whether it hit the star along its path).  This means that a 0 inclination we get the correct result, but at 90 degrees none of the photons is stopped by the star.

So the question is whether it is better in walls to check the path to see if has hit the star, or to do this in ds_to_wind.  

The advantage of doing it in ds_to_wind is we don't ever let the photon go to a place that it should not legitimately reach

The advantage of doing it in walls, is that this is closer to where the actual problem Mandy uncovered is.  This is also where we deal with hitting the disk.

Or we could practive a belt and suspenders approach

**Comment by mandyhewitt** [comment] 2019-11-05 13:30
@kslong I reran my models on dev and apart from having to use atomic data file standard80, I can now confirm that the issue appears to be resolved. Here are my plots after the fix.

![postknoxfixall](https://user-images.githubusercontent.com/32335653/68211595-ca5e4680-ffcf-11e9-8741-f4c92016115f.png)


![Screenshot 2019-11-05 at 13 28 35](https://user-images.githubusercontent.com/32335653/68211826-393b9f80-ffd0-11e9-9a81-e03d05db3c03.png)

I'm happy for this to be closed now.

**Comment by kslong** [comment] 2019-11-05 15:25
The issue of spherical models producing different fluxes at different inclination angles appears solved  and so I am closing it.  @mandyhewitt @ssim I do remind you for the specific model (.pf) file that was used to study this error, it looks like to me the ionization solver is not working because when I run windsave2table I find that the relative abundances of, for example, H do not make sense.  If this model is totally non-physical, then one may not care.  But if you do care, you need to open a different issue about this, and probably enlist some one like @Higginbottom to look into it more.

**Closed as completed by kslong** 2019-11-05 15:25 UTC
Labels: bug
