### ISSUE TITLE
rtheta grid has angles > 90 degrees that are "inwind"

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#523] opened 2019-06-05 11:38 UTC
I've been fiddling around with rtheta grids for some spherical models and I'm noticing that I have cells that are classified as "in the wind" (i.e. inwind = 0) with angles > 90. There are two out of three cells with this theta>90 that have inwind == 0. 

I understand there need to be "ghost cells" in python, but I don't actually know why there are 3 (note there are also three in cylindrical coordinates). If this is correct, then I don't think we should be setting inwind to 0 for these cells, because they appear in things like convergence statistics and no photons ever get to them.

Also, the x and xcen values of these cells are not actually consistent if you inspect rtheta_make_grid (), and it's inconsistent with what's done in hydro (I think). So we should probably figure this out at some point.

**Comment by kslong** [comment] 2019-07-05 14:40
Can you provide an example of this.  I don't see it when I run the attached .pf file
[test.pf.txt](https://github.com/agnwinds/python/files/3363116/test.pf.txt)

**Comment by jhmatthews** [comment] 2019-07-10 14:40
Use case: if you run the attached model, then there appear to be cells on the outer edge of the grid that have very small z values:
[template.pf.txt](https://github.com/agnwinds/python/files/3378016/template.pf.txt)

These cells get no photons, but do have a density and contribute to convergence statistics. Thus, a fully converged model might get reported as not converged. They also seem to be included in the wind (i.e. their inwind values are >=0). 

The portion of the code I am referring to above, regarding inconsistency of x,xcen and theta,thetacen, is here (line 191 of rtheta.c):

```C
      /* Only the radial distance can be logarithmic */

      theta = w[n].theta = dtheta * j;
      thetacen = w[n].thetacen = w[n].theta + 0.5 * dtheta;
      if (theta > 90.)
      {
        Error("Angle greater than 90!!\n");
        theta = 90.;
      }
      if (thetacen > 90.)
      {
        thetacen = 90.;
      }


      /* Now calculate the positions of these points in the xz plane */
      theta /= RADIAN;
      thetacen /= RADIAN;
      w[n].x[1] = w[n].xcen[1] = 0.0;

      w[n].x[0] = w[n].r * sin (theta);
      w[n].x[2] = w[n].r * cos (theta);

      w[n].xcen[0] = w[n].rcen * sin (thetacen);
      w[n].xcen[2] = w[n].rcen * cos (thetacen);
```

**Comment by kslong** [comment] 2019-07-17 14:25
Here is a snapshot of one set of cells at a particular radius 
![screenshot_94](https://user-images.githubusercontent.com/2530901/61383370-257afa80-a874-11e9-8af6-6ded6ea41cbd.png)

The last 3 cells have angles of 90, 93.3, and 96.7 degrees and theta_cen of 91.7, 95.0 and 98.3,  all but the last cell has a positive volume, are regarded as in the wind, and have convergence criteria.  None of the last 3 cells has any photons.

This situation is different from a cylindrical grid, where we have two ghost cells on the outside edges.  ksl's belief for the reason we need two ghost cells, is that we need all 4 corners of one ghost cell, and to get the two outside corners we have to add another wind cell.   Neither of these cells is in the wind, and neither appears to have any volume, although one might need to be careful about what this means; it's possible windsave2table looks to see if a cell is in the wind and zeroes out various quantities.

If this argument were correct and the whole story, it would suggest we only need two ghost cells, in that case as well.

**Comment by kslong** [comment] 2019-07-17 20:36
@jhmatthews said that these "ghost" cells are contributing to the convergence statistics, but that is probably not correct.  If one looks at the template.0.master.txt file, one observes that densities, etc for j=29, that is the theta direction, are the same as 28.  What this means is that j=29 has the same plasma cell as 28.  The convergence statistics are constructed by summing over elements of the plasma ptr, not of the wind cells.  

What is definitely a problem is that j=28 is showing up as inwind. This is a problem because inwind is part of the WindPtr.  (Note, I have confirmed that windsave2table gets nwind from WindPtr, so there is no question this is a problem.)

**Comment by kslong** [comment] 2019-07-17 21:15
...hmm. This is the check that should have found that the edge cells are not in the wind

```

  if (i >= (ndim - 2) && j >= (mdim - 2))
  {
    return (W_NOT_INWIND);
  }
```
around line 775 of rtheta_is_cell_in_wind in rtheta.c.  But why is this and && and not || since we want to find the two boundaries.  The logic is similar for cylndrical winds, which I also do not understand.

**Comment by kslong** [comment] 2019-07-18 14:35
Summary

- The problem with ghost cells appearing in the wind has been fixed. (The logic discussed in the previous comment was incorrect; the two possibilities should have been "or'd". 
- There should really only be two ghost cells along the disk axis (at most) and there were in fact 3. This has also been fixed.  The first ghost cell has theta of 90 degrees and the second one somewhat greater.
- Although some of the tables created with windsave2table made it appear that ghost cells were being included in convergence summaries, the were not as convergence is determined by looking at the PlasmaPtrs.  (Note that there was an error, but the error was that the 90 degree cells were treated as real, and not ghost cells.)
-Although I have looked a bit at how the hydro import is done, I have not tried to sort this out.  Any changes here need to be coordinated with @Higginbottom 

@jhmatthews It would be good for you to review all of this, and see whether we can close this.  I have not dealt with the question of the x and xcen values, because I did not understand what the actual concern was.  I would not be surprised if these were slightly different the hydro grid may be set up slightly differently to accommodate the incoming file format.

**Comment by kslong** [comment] 2019-07-19 14:37
Knox and James agreed this issue can now be closed.   At some time in the future, it may be worthwhile to look at the consistency of approach between the way the grid is set up for the Zeues/Plutho models and for our general rtheta approach, but we will leave that for another time.

**Closed as completed by kslong** 2019-07-19 14:37 UTC
Labels: Release
