### ISSUE TITLE
Domains: Still failing on spherical winds around AGN

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#210] opened 2016-05-04 16:17 UTC
Domains are still failing on spherical winds around an AGN. Weirdly, photons do not seem to be propagating beyond cell 1:

```
ntot 
   z\x   6.41e+12 7.07e+12 7.80e+12 8.60e+12 9.48e+12 1.04e+13 1.15e+13 1.27e+13 1.40e+13 1.54e+13 1.70e+13 1.88e+13 2.07e+13 2.28e+13 2.52e+13 2.77e+13 3.06e+13 3.37e+13 3.72e+13 4.10e+13 4.52e+13 4.98e+13 5.49e+13 6.06e+13 6.68e+13 7.36e+13 8.12e+13 8.95e+13 9.87e+13 1.09e+14 1.20e+14 1.32e+14 1.46e+14 1.61e+14 1.77e+14 1.95e+14 2.15e+14 2.38e+14 2.62e+14 2.89e+14 3.18e+14 3.51e+14 3.87e+14 4.27e+14 4.70e+14 5.19e+14 5.72e+14 6.30e+14 6.95e+14 7.66e+14 8.45e+14 9.32e+14 1.03e+15 1.13e+15 1.25e+15 1.38e+15 1.52e+15 1.67e+15 1.84e+15 2.03e+15 2.24e+15 2.47e+15 2.73e+15 3.01e+15 3.31e+15 3.65e+15 4.03e+15 4.44e+15 4.90e+15 5.40e+15 5.95e+15 6.56e+15 7.24e+15 7.98e+15 8.80e+15 9.70e+15 1.07e+16 1.18e+16 1.30e+16 1.43e+16 1.58e+16 1.74e+16 1.92e+16 2.12e+16 2.33e+16 2.57e+16 2.84e+16 3.13e+16 3.45e+16 3.80e+16 4.19e+16 4.62e+16 5.10e+16 5.62e+16 6.20e+16 6.83e+16 7.53e+16 8.31e+16 9.16e+16 1.01e+17 
6.41e+12 15633965 15633965        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0 
```

This doesn't seem to be a sensible physical phenomenon. As of ionisation cycle 10 (when it fails) we get a photon scatter output of:

```
No. of photons which have scattered n times
   287198039114193 78552 58436 46021 37423 30732 25945 22430
 18999 16720 14582 13190 11867 10773  9687  8942  8134  7637
  7006  6365  6051  5628  5289  4997  4824  4546  4356  4031
  3869  3692  3535  3362  3199  3072  2928  2892  2695  2594
  2604  2493  2365  2374  2321  2172  2098  2017  1877  1824
160335
Number of photons resonantly scattering n times
992993  6578   422     7     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0
```

Compared to (for a non-Domain2 run):

```
No. of photons which have scattered n times
817202127859 34939 11751  4650  2204   897   313   127    40
    14     2     2     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0
Number of photons resonantly scattering n times
906976 63428 18513  6561  2700  1291   416    90    21     4
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0
     0
```

Here's the input files I've been using:
[sphere_domain.pf.txt](https://github.com/agnwinds/python/files/249160/sphere_domain.pf.txt)
[sphere_non_domain.pf.txt](https://github.com/agnwinds/python/files/249161/sphere_non_domain.pf.txt)

**Comment by kslong** [comment] 2016-05-05 18:53
This seems strange.  The problem is not occuring on 1d_sn one of our regression tests of the homologous model.

**Comment by kslong** [comment] 2016-05-06 19:30
@smangham  I am closing this problem, as it it should now be fixed.  As noted, above there was a check of the inputs in homologous.c that caused the grid to be set up incorrectly.   Photons now propagate through the entire grid.

**Closed as completed by kslong** 2016-05-06 19:30 UTC
