### ISSUE TITLE
extract versus total spectrum

### ISSUE THREAD

**Issue by ssim** [sirocco-rt/sirocco#39] opened 2013-08-13 15:30 UTC
I have been doing these 1D (spherical) test problem for comparison with ARTIS. 

I have noticed that in the spectrum file the (.spec) the spectrum in the "Emitted" column does not always agree with what is in the spectrum computed for a particular viewing angle. 

I'm a bit confused by this. I thought that the "Emitted" column just comes from binning the escaping packets, while the end columns depend on the extract method (I have live.or.die set to 1). However, for a spherical model the spectrum should be orientation independent and so I had expected that these should be the same. 

If this is a bug then it seems a little odd - I'm finding better agreement with TARDIS from the angle dependent (extract) spectrum than the "Emitted" column.

The plot below shows an example of what I mean for the case of a Ca II line. 

I've not done any real testing yet to try and understand this.

![ca](https://f.cloud.github.com/assets/790317/955601/4643f0e2-042d-11e3-88c5-e22b3c3e497d.png)

**Comment by kslong** [comment] 2013-08-15 14:28
I think this is pretty weird.  Emitted is just the sum of all of the photons that escape from the wind in any direction, and of course for a spherical model should be the same as the photons that are extracted.

Things to check:

Is the extracted spectrum the same in all directions.  Select a variety of polar angles and check these.
Is it possible, that photons which hit the star are being included in the "Emitted" spectrum.  Do we see the same effect for a star that is small compared to the size of the sind?
Has this behavior changed over time.

(Note, I know we have made some changes in the spectra that are printed out.  I have been somewhat surprised by the various problems associated with this area of the code, as in the era of LK03, I checked a lot of these sorts of things.  At that time, I don't believe I had implemented spherical coordinates, but I can't see how coordinate systems would affect this portion of the code),

I believe we should sort this out.

Knox

**Comment by ssim** [comment] 2013-08-15 16:56
I did check (for a couple of cases) that the extract spectrum is the same for different directions. More than that I've not looked into so far.

**Comment by ssim** [comment] 2013-08-23 19:48
Here is a comparison between "extract" and the direct counting spectrum for a simple case. This time I've not done any ionization cycles and have switched on the "pure absorption" line transfer mode. You can see that this looks reasonably ok. This suggests to me that the problem is something to do with the scattered packets.

![pure_absorption](https://f.cloud.github.com/assets/790317/1018535/e9b1555c-0c2b-11e3-9265-b8c7618661f4.png)

However, here's the equivalent comparison for line_transfer mode 3 (the standard type) - and again this is without doing any ionization cycles (for simplicity). This time I'm also showing contributions to the extract spectrum using the options to select number of scatters (it shows "0" scatters, "0"+"1", "0"+"1"+"2", and all). As you can the extract spectrum is building up ok when combining the different numbers of scatters but the spectral feature doesn't match up to the packet binning case but it is closer than in the case at the top of this page (where ionization cycles were carried out too).

![line_mode_3](https://f.cloud.github.com/assets/790317/1018591/ef5b50f6-0c2c-11e3-9ef2-03d9da4f1a09.png)

**Comment by kslong** [comment] 2013-08-24 17:17
So, I took a quick look at this.

For an extracted resonance photon, it is pretty obvious what happens with regard to Doppler shifts.

For the emitted spectrum, which is I guess, what Stuart means by the packet binning case, I'm having trouble finding where the Doppler shift actually occurs.  I expected it the routine scatter (line 1094 in resonate.c) which is called by trans_phot.

The description to scatter says it calculates the new direction and frequency of the photon, but I don't see a frequency calculation anywhere.

This code in trans_phot also looks odd; why are we setting nnscat to 0 and then incrementing it and then calling scatter

   nnscat = 0;
              nnscat++;
              ptr_nres = &nres;

```
          /*74a_ksl - Check added to search for error in weights */
          if (sane_check (pp.w))
            {
              Error
                ("trans_phot:sane_checl photon %d has weight %e before scatter\n",
                 nphot, pp.w);
            }
          if ((nerr = scatter (&pp, ptr_nres, &nnscat)) != 0)
            {
              Error ("trans_phot: Bad return from scatter %d at point 2",
                     nerr);
            }
          pp.nscat++;
          /* 74a_ksl - Check added to search for error in weights */
```

It's pretty clear to me that this is yet another area of the code that needs more consistent commenting, and I think it has been Stuart and I who are the culprits in this case.

**Comment by jhmatthews** [comment] 2014-01-22 17:52
I've been looking into this a little as it would be nice to get it ticked off and understood. The extract spectrum is obtained in extract_one()

``` C
      k = (pp->freq - s[nspec].freqmin) / s[nspec].dfreq;

      /* Force the frequency to be in range of that recorded in the spectrum */

      if (k < 0)
        k = 0;
      else if (k > NWAVE - 1)
        k = NWAVE - 1;

      /* Increment the spectrum.  Note that the photon weight has not been diminished
       * by its passage through th wind, even though it may have encounterd a number
       * of resonance, and so the weight must be reduced by tau
       */

      s[nspec].f[k] += pp->w * exp (-(tau));    //OK increment the spectrum in question
```

whereas the emitted, and other columns, are created in create_spectrum() later on:

``` C
/* lines to work out where we are in a normal spectrum */
      k = (p[nphot].freq - freqmin) / dfreq;
      if (k < 0)
    {
        nlow = nlow + 1;
        k = 0;
    }
      else if (k > NWAVE - 1)
    {
      if (((1. - freqmax / p[nphot].freq) > delta) && (geo.rt_mode != 2))
        nhigh = nhigh + 1;
      k = NWAVE - 1;
    }

      if ((i = p[nphot].istat) == P_ESCAPE)
    {
      s[0].f[k] += p[nphot].w;  /* emitted spectrum */
      s[0].lf[k1] += p[nphot].w;    /* logarithmic emitted spectrum */
      s[0].nphot[i]++;
```

Which looks the same to me. I have a hunch about Fnu and Flambda which I'm looking into...

Edit: Alas my hunch was wrong. Still drawing a blank on this one.

**Comment by jhmatthews** [comment] 2014-10-07 11:15
This was caused by the problem #117 and fixed by https://github.com/agnwinds/python/commit/ecaf30d94e1caa97b990db4552030a4272a1e403.

Results are on a page [here](https://sites.google.com/site/agnwinds/current-work-in-progress/tardis-v-python/spectral-comparisons). Clearly fixes it, so closing.

**Closed as completed by jhmatthews** 2014-10-07 11:15 UTC
Labels: high
