### ISSUE TITLE
Imported Model Creating Different Winds(?)

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#476] opened 2019-02-25 14:50 UTC
As suggested in the previous telecon, I tried running a macro atom model using an imported model in hopes of meaning that a macro simulation would take a little less time to run - this worked.

At the end of the run, I compared the simple and imported macro run but noticed that the wind geometry was different. The wind for the imported model looked thinner than the "from scratch" wind of the simple atom model.

To make sure that I wasn't messing anything up, I ran the simple atom model again from scratch and using the wind from this model as an imported wind model. Same thing as with the macro model and this time I noticed that the spectra were different as well,

[tdeStar.pf.txt](https://github.com/agnwinds/python/files/2901052/tdeStar.pf.txt)
![image](https://user-images.githubusercontent.com/19627279/53345871-c987f780-390d-11e9-8e0f-30793be3416b.png)

I've talked to @kslong about this briefly and he seems to think that my issue could be casued by the imported model routines expecting the velocities and densities to be at the same place in the grid (which he thinks was the case for the FU Ori models), whereas in Python models the velocities are defined at the edges of the cell and the densities at the centre. His proposed fix is to have some sort of switch to handle the two separate cases.

**Comment by kslong** [comment] 2019-05-04 15:01
@saultyevil   ... so is the way to reproduce this as follows:

run the .pf file above
run the program that creates an imported model file from an run of python, e.g. import_cyl.py
run this as an imported model.

**Comment by saultyevil** [comment] 2019-05-07 09:20
That's right Knox. I'll update Python to the latest dev branch and try and re-run the test again in light of the changes you made due to issue #505 to see if anything has changed.

**Comment by saultyevil** [comment] 2019-05-07 13:47
So, I re-ran the (old) TDE model in the original post and unfortunately it looks like there still might be a problem with imported models - I should note that this model is low resolution at 30x30 cells. 

![tde_model_comparison](https://user-images.githubusercontent.com/19627279/57303207-bf843100-70d4-11e9-9527-44f4e10f0c5c.png)

I had a quick look at the wind as well, and it appears that the shape of the wind is different between the two models (imported is on the left, regular sv wind on the right).

![Screenshot from 2019-05-07 14-38-50](https://user-images.githubusercontent.com/19627279/57303838-150d0d80-70d6-11e9-898c-699865a9d3b3.png)

I used the following files for these simulations:
[tde_model.pf.txt](https://github.com/agnwinds/python/files/3152916/tde_model.pf.txt)
[tde_model_imported.pf.txt](https://github.com/agnwinds/python/files/3152920/tde_model_imported.pf.txt)
[tde_model.import.txt](https://github.com/agnwinds/python/files/3152922/tde_model.import.txt)

**Comment by saultyevil** [comment] 2019-05-07 14:07
Interestingly, when I plot the spectrum components of the two models, the wind components are slightly different (which I expected but maybe I actually expected a bigger difference), and the disk components between the two models is quite different.. which I didn't expect. Naturally, this also effects the created and emitted components.

![tde_model_spec_comps](https://user-images.githubusercontent.com/19627279/57305603-420eef80-70d9-11e9-86af-fe049b5fc840.png)

Using diff suggests the difference between the two parameter files is only associated with setting up the wind. Not too sure what this means...

**Comment by kslong** [comment] 2019-05-07 14:21
What is needed is to use windsave2table to compare the model before importing and after importing.  Knox

**Comment by kslong** [comment] 2019-07-19 00:07
There may be some issues here, but one should not expect precisely the same answers from the imported model as the original one. This is because cells which are not completely in the wind, are ignored with a imported wind.  Additionally, there is some "smooothing" because for imported models we assume everything is centered on the grid point, but within python we assume densities are cell-centered, which requires some interpolation.  

That said, I do not understand for the simple cv model I tried, why if I went

py cv
windsave2table cv
import_cyl.py cv
py cv_import
windsave2table cv_import
import_cyl.py cv_import

that I found that rho seems to be lower in cv_import.import.tx than in cv v.import.txt

**Comment by kslong** [comment] 2019-07-19 21:14
There was a definite problem here, which was affecting all imported models.  The basic issue was that rho was being assigned to the wrong cell.  This should now be fixed for all coordinate systems.

**Comment by kslong** [comment] 2019-07-19 22:52
Summary:
- There was an issue with the imported models.  rho was not being placed in the right cell, but in one cell "too high" in all of three types of coordinate systems. This has now been fixed.
- One should not expect a parameterized model, and an imported model from the parameterized model to produce exactly the same results, because imported models do not have partial cells.  The effect should be small for models with large numbers of cells.
- The way imports work is we assume that rho is being provided for the center of a cell, whereas positions and velocities are provided for the edges of cells.  This is the Python convention.  If some provides an imported model, she may provide all of the variables at the same location; in that case, Python will not represent the model exactly.

@saultyevil  I am closing this issue at this point.  You may want to check how your tde models look now as an example.  Basically what I have done is confirm that the process outlined a few comments earlier produces the same grid before and after running the procedure outlined several comments earlier.

**Closed as completed by kslong** 2019-07-19 22:52 UTC
Labels: bug, Release
