### ISSUE TITLE
matrix_ion failing

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#387] opened 2018-06-07 21:45 UTC
@jhmatthews and I are trying to model FU Ori stars, and one of the problems we are having is that matrix_ion fails to work in most cases.  However, this is not limited to that situation,  there are rate_matrix failures, which give rise to errors that say the determinant is zero, in a number of the regression tests, including cv.pf 

In the case of cv.pf, the rate matrix problems go away if you modify the data file so that Fe is excluded.  One might imagine that the problem is that Fe has some ions that have extremely high ionization thresholds and that perhaps the the data that goes into making the rate equation is the problem.  

However, if one runs the same model, except that one keeps only H, He, and Fe, the errors do not appear.  Thus it seems likely that the fact that we cannot invert the matrix, or rather that the determinant goes to zero has to do with the fact that we solve the rate matrix for all of the ions at once.  

It's not obvious to ksl that we needed to do this, since we don't include any nuclear reactions that would change one element to another.  An alternative would be to set up a rate matrix equation for each element, or some set of them perhaps.  This would have the advantage of allowing us more insight into where the problem actually was as well.

At any rate, @Higginbottom and @jhmatthews  I think this is a problem we ought to collectively address with some urgency.

**Comment by kslong** [comment] 2018-06-13 20:05
@Higginbottom is testing a possible fix for this problem.  Here is a test file that approximates the physical situation for the FU Ori case, which prompted the original concern.  This .pf file runs on the dev branch, and gives matrix_ion errors.  One could probably shorten the number of ion cycles, and eliminate the spectral cycles.

[low_temp.pf.txt](https://github.com/agnwinds/python/files/2099704/low_temp.pf.txt)

**Comment by Higginbottom** [comment] 2018-06-14 07:40
OK, so I have run that example:
errors before:
        7 -- getatomic_data: line input incomplete: %s
     1971 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        6 -- error_count: This error will no longer be logged: %s
       32 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d
      500 -- Rate Matrix Determinant is %8.4e for cell %i
      500 -- matrix_ion_populations: bad return from solve_matrix
      500 -- matrix_ion_populations: Unsolvable matrix! Determinant is zero. Defaulting to no change.
      500 -- ionization_on_the_spot: nebular_concentrations failed to converge
      500 -- ionization_on_the_spot: j %8.2e t_e %8.2e t_r %8.2e w %8.2e nphot %I

errors after the change to using the log version of the determinant

        7 -- getatomic_data: line input incomplete: %s
     1971 -- Get_atomic_data: more than one electron yield record for inner_cross %i
        1 -- error_count: This error will no longer be logged: %s
       32 -- get_atomicdata: No inner electron yield data for inner cross section %i
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d

So it is only the determinant calculation that is screwing things up.

I'm going to call this fixed - but what we need is an example of the .pf file that caused the initial problem that Sam fixed with the determinant check. In other words we need to see a situation where the gsl code throws horrible errors.....

N

**Comment by Higginbottom** [comment] 2018-06-14 10:06
This is mentioned in issue #196 (new closed) but this is when we have very small numbers of photons. No pf file was attached so I can't reproduce the older error.
The inclusion of the determinant test was pulled as part of update #192, so this predates error #196...
I think the reason it just started flagging lots of really serious errors is that Sam merged in a huge commit on the 5th May (#372), that included a change he made last summer ( which actually bailed out of matrix ion when there was a zero determinant. Before that, it just flagged an error, but carried on trying to solve the matrix. Since it usually succeeds, we ended up with OK populations. 
I think...
Anyway, to go any further, I need a pf file that actually makes the gsl*solver* fail with a zero determinant error. Then I might be able to see if there is really any benefit to modifying the code to eliminate lines etc.

**Comment by kslong** [comment] 2018-06-14 13:42
@Higginbottom  @jhmatthews @lazygun37  I am confused.  I do not believe that if the rate matrix determinant was actually 0, that one can solve an equation of this type.   I know that was what I was taught in grad school.   We are trying to solve R * n = m As I understand it, solving an equation like this, basically means you have been able to replaced R  with A_-1 lambda A, where lambda is an eigenvector (or eigenmatrix)  with only values in the diagonal elements and A was essentially a rotation matrix (with determinant 1).   In this case, one we have lambda A n = A *m ->    A n = lambda_-1 A m --> n= A-1 lambda -1 A m.  

While various methods use a different approach to solve numerical errors, a determinant of 0, means one of the elements of the eigenvector is 0, and in this case there is some combination of values in n that is indeterminable.    

So it seems to me, either determinant is not actually 0 (in which case why doesn't gsl report this), or it is, and something must be amiss.  And if it is very close to zero how accurate are our inversions.

**Comment by Higginbottom** [comment] 2018-06-14 14:03
The matrix determinant is *not* zero in the cases that were throwing errors. It was less than 1e-300.
In very hand waving terms, the determinant is lots of cells multiplied together in a complicated way.
The more of those cells that are themselves very small, the smaller the determinant becomes. The matrix is still totally reasonable, but often for low T radiation fields, you get quite a few PI rate coefficients of less than 1e-30. I think this is why you had the odd behaviour of simply removing a bunch of elements which made the code run. You just multiplied fewer factors of 1e-30 together.

In the log version of the determinant calculation, you can end up with ln(det)=-300, or -400 etc. There is nothing wrong with the matrix, it just has a very small determinant.

does this make sense?

Oh, and I don’t think the LU decomposition method actually *uses* the determinant, so I don’t think that the accuracy is necessarily affected  by having a tiny one. Clearly if it really is zero, then this means the matrix cannot be inverted even by LU deccomp - but I don’t have a case to examine at the moment when this happens….

N

**Comment by jhmatthews** [comment] 2018-08-09 09:09
@kslong @Higginbottom are we satisfied that this issue is largely resolved? can we close it? I'm sure there are still improvements that can be made, but there is an issue open here for this: https://github.com/agnwinds/python/issues/196

**Comment by Higginbottom** [comment] 2018-08-09 09:16
I'm happy that we know what is going on - and what was causing this particular error..
Lets close!

**Comment by kslong** [comment] 2018-08-09 14:42
I am happy for us to close the issue, though I'd like a summary of our conclusion here.   @Higginbottom  @jhmatthews 

Is it as follows

The actual issue was NOT that LU decomp was returning an error but a test we were conducting, namely calculation of the determinant was failing.  We had put the test in because we felt that if the determinant was non-zero then we were reasonably confident that the LU decomp was accurate.

Now, we are arguing that LU decomp can still be accurate even if the determinant is very small.   We know that LU decomp will fail is the determinant is identically zero, but we also know also that LU decomp is designed in part to mitigate the possibility of a small but non zero determinant.

(There is a whole literature out there on the accuracy of LU decomp and other techniques.)

So our actual solution was to remove the determinant check (or at least it's effect) and to set the concentrations to what were given by the LU decomp.

I am going to reopen this, but if my summary is correct, then you should so state and close it again.

**Comment by Higginbottom** [comment] 2018-08-09 14:58
You are almost correct Knox. Actually we do still test to see if the determinant is zero. I have just modified the code to use the log version of the gsl routine to calculate the determinant. This massively increases the dynamic range it can cope with.
So, if the determinant is *still* zero, it will still error.

**Closed as completed by Higginbottom** 2018-08-09 14:58 UTC
Labels: bug, high

**Comment by kslong** [comment] 2018-08-09 17:25
Thanks, @Higginbottom   This is clear.
