### ISSUE TITLE
DFUDGE in spherical shell models

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#694] opened 2020-04-23 16:19 UTC
This is an old problem, that I'm bringing up again coz I spent a day boggling over it.

I have been trying to understand some aspects of flux logging in a 1D model in python, and as part of this I dis-interred some old tests. And got odd results, until I remembered that I'd had to hack python to get it to work.

Here is a spherical model - it is a thin shell..

[model.txt](https://github.com/agnwinds/python/files/4523753/model.txt)

if we run this in python, a59922445f878a1ffe0bbc262432b09c54e2dde9 

[shell2.pf.txt](https://github.com/agnwinds/python/files/4523759/shell2.pf.txt)

then we can obtain a value for the flux in the cells. We can calculate this by hand, and here is a plot of the flux vs theta for py84c (labelled standard) with the by hand flux as the black line.

It is low, and the reason for this is that DFUDGE is automatically set to 1e5 for this model. The shell is 1e6 thick, so photons miss 10% of the cell. If I hack python to set DFUDGE to 1, then I get the other line

![Flux_by_bin](https://user-images.githubusercontent.com/3329213/80122994-30428880-8586-11ea-9b7f-23e3cef12733.png)

Is this a problem in normal models? Not sure, although the reason I was digging was to look at a problem in my stellar wind models - so it might be.

However, it does point to an issue in automatically calculating DFUDGE, which has caused a lot of problems in the past. 

I think the issue causing DFUDGE to be large, is that the minimum radius used to calculate it might be being set to 0.0 because there are cells with a cartesian coordinate x=0.0. Should we use a radial measure in a spherical model. Not sure, just want to make sure we discuss this and agree on wether to work on it.

**Comment by kslong** [comment] 2020-04-23 20:30
So just to be clear,  Nick, this is a 2d model not a 1d model of a spherical shell, which is what I assumed originally. So whatever one chooses DFUDGE to be it must apply to all spherical polar models, whether they are actually spherical or not.  This shell has a thickness of 1e6 cm,  placed a a distance of 1e11 cm.  

I do agree however that something is odd:

For imported models rmin is set in import_rtheta.  It looks like it is setting rmin to the minimum radius ... but it looks like rmin is being set for any cell, and not restricting things to cells that are in the wind.  This looks like a mistake.

In your example, you have cells that are not in the wind with a size of 10e10, but your first real cell is at 1e11.  This means the program is finding that the thickness of the wind is about 1e11.

If you look at setup_dfudge (in setup.c), you will see that in this size range DFUDGE, as determined by Rmax, DFUDGE is set to 10e5, as you said.  

I suspect, that making this change will fix your specific problem, because this will make dr less than 1e8, in which case DFUDGE is set to delta r/1000

Since we are looking at the problem though, we should decide whether this fixed value of DFUDGE for the range between 1e8 and 1e15 is what we want.  Outside this, we use something that is proportional to the size difference between the inner and outer edge.

**Comment by kslong** [comment] 2020-04-27 19:21
There is an additional problem here  that windsave2table fails on this model with a segfault.  

It does not fail on a simple spherical model, nor does it fail when you create a model directly from a previous spherical model, run that and then try running windsave2table.  It only fails when you run windsave2table on the input files above.

***This problem seems to be occurring only on my Mac, and not on linux***

This was a problem in windsave2table where the variable start was not dimensioned large enough.

**Comment by kslong** [comment] 2020-04-27 22:50
@Higginbottom can you recheck this on dev.  At present, I get 1e3 cm for DFUDGE, this being (rmax-rmin)/1000, because in setup.c delta is 1e6. and when I look at the code it's clear that some of my analysis above was wrong, at least as the code is  written today.  Possibly @saultyevil has already been working on this, and made some changes that affect the number.

**Comment by Higginbottom** [comment] 2020-04-28 09:09
I agree, I also get 1e3cm - not quite sure what has caused the change. I think Ed modified how rmin is set - from the model rather than from an input in the parameter file. It should be possible to code something up that works out the smallest distance across a cell - dr or rdtheta for a spol grid, or the smallest of dz/dx in a cartesian/cyclindrical grid. I shall take a little look..

**Comment by Higginbottom** [comment] 2020-04-28 10:07
Hmmmm, made somewhat more tricky by the fact that the grid is set up *after* setup_dfudge is called...
Hmmmmm

**Comment by saultyevil** [comment] 2020-04-28 10:24
Yeah, I think my latest changes would be what's made the difference to DFUDGE. Previously, because the boundary code was using degrees instead of radians, Rmin would be negative in model.txt, so 1e8 < delta < 1e15, which explains why DFUDGE = 1e5. With it fixed now, it's calculating DFUDGE more appropriately. 

I encountered the similar problem with setup_dfudge() though, Nick... it's why I moved all of the boundary calculations for imported models to before we set it up. Though, I don't think we can move where setup_dfudge() is. I found out the hard way that DFUDGE is used somewhere in define_wind() (I can't remember where right now)...

**Comment by Higginbottom** [comment] 2020-04-28 10:25
Yeah, just found that out myself via moving it and seeing what happens - bad things, bad things happened.
But, I think it is plausible to add more checks into the wind_check routine....
Pottering...

**Comment by Higginbottom** [comment] 2020-04-28 13:56
OK, nearly got a general check for size of cells - I've never used the cyl_var geometry, and there doest seem to be an example. Anyone got an example I can play with???
Will try and make one to be going on with..

**Comment by Higginbottom** [comment] 2020-04-28 14:10
OK - I think cylvar can be treated exactly as cylindrical

**Comment by Higginbottom** [comment] 2020-04-28 15:03
Hmmmmmm, running tests, it seems that the changes Ed made actually fix the DFUDGE bug even in very extreme thin shell models. I may have rather hated my time today.. Should have run some more checks to start off with...
Hmmm

**Comment by kslong** [comment] 2020-04-28 15:09
I believe what Ed did was to address the first of the issues I pointed out earlier.  He made sure that one only counted cells within the wind in establishing dfudge, which depends both on rmin and rmax.  We need to make sure this happens properly for the other import types, but then I suspect we are in reasonable shape.

There is a separate question about whether it makes sense to modify the way DFUDGE is calculated in setup.py, which looks a bit arbitrary.  I think the choices there are historical, but one could image saying that we go with (xmax-xmim)/10e5 or something everywhere.  The question is whether we will run into some problem intersecting the windcones if we do this.

**Comment by Higginbottom** [comment] 2020-04-28 15:15
My new code checks over the grid, and works out the minimum distances between cell boundaries  in the model. I was just about to get it to compare this to defudge and then set dfudge to say 1% of that value if smaller..
Then I did some pre-change testing on my extreme thin shell, and saw Ed's fix had already fixed it.

**Comment by kslong** [comment] 2020-04-28 15:30
I am not sure, Nick, from this last comment, whether you were thinking of pushing this kind of change into dev.

Historically, we have also had problems if we made DFUDGE too small in objects that were themselves quite large, e. g. AGN.  We had a big concern in the past that for large objects, e.g AGN, that we some of the calculations to find the wind cones were failing because of roundoff or other errors if you made dfudge too small.  We have to remember that DFUDGE has to work in these cases as well as the one you are currently concerned with Nick.

P. S. We might want to move this conservation to Slack, as it is getting very long.  Then we can summarize our conclusions once we have them.

**Comment by Higginbottom** [comment] 2020-04-29 09:12
Ran regression - all fine. I was planning on pulling this in - I think it is a correct approach that should capture problems in the grid - its certainly not just aimed at my current problem.

**Comment by Higginbottom** [comment] 2020-04-29 10:31
A hopefully final fix to this problem now pushed.

**Comment by kslong** [comment] 2020-04-29 11:02
We need to talk about this so we are all agreed.

Sent from my iPhone

On Apr 29, 2020, at 5:31 AM, Higginbottom <notifications@github.com> wrote:

﻿

Closed #694<https://github.com/agnwinds/python/issues/694>.

**Comment by Higginbottom** [comment] 2020-04-29 11:04
KSL has asked me to work out why moving the DFUDGE calculation to after the call to define_wind in python.c causes a crash. To kick off with, running the 1d_sn example  - the code crashes very soon after starting to fly photons with 

        1 -- Ignored %d collision strengths with no matching line transition
        1 -- Ignoring %d inner shell cross sections because no matching yields
        1 -- wind2d.c: Not currently able to calculate mdot wind for coordtype %d in domain %d
        1 -- check_grid: optical depth may be high in %i
        1 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
      593 -- spherical: ds_in_cell s and smax returning VERY_BIG in cell %i nudging photon by DFUDGE
   100001 -- calculate_ds: v same at both sides of cell %d
        3 -- translate_in_wind: Grid cell %d of photon is not in wind, moving photon %.2e
        3 -- translate_in_wind: photon %d position: x %g y %g z %g
        2 -- error_count: This error will no longer be logged: %s

**Comment by Higginbottom** [comment] 2020-04-30 10:39
OK, so the reason why it falls over if you don't set DFUDGE before define_wind is that the individual w[n].dfudge for each cell is set to DEFUDGE as almost the first step in define_wind. This is not touched again, but if it is set to 0.0 then you end up in a world of trouble...

**Comment by kslong** [comment] 2020-05-04 23:03
@Higginbottom @saultyevil   I have pushed a new remote branch bug694_dfudge, which contains an attempt to do what I think we agreed at our splinter last week.  If adds definitions the cell-based dfudge for use in the wind for spherical, cylindvar and rtheta coordinates.  It removes the assignments of DFUDGE in wind_check, but should throw errors if DFUDGE is larger than the criteria Nick set.  These changes do cause the regression tests to change a bit, because this is a change that modifies path lengths enough that different random numbers are generated.  The regression tests show this, although the spectra look pretty much the same.  Nick;s shell2 .pf file looks OK to me.  I would appreciate your doing a few checks on your favorite models before I merge these changes into dev.

**Comment by Higginbottom** [comment] 2020-05-07 14:28
I have stress tested this on my nasty thin shell models and my finely gridded stellar models and it appears to work fine. There is one bug - in my work - which I cannot work out how to push back to the branch. 
The check in wind_check, for a spherical wind, 

if (drmin < delta || dtmin < delta)

should only be 

if (drmin < delta)

since dtmin is undefined and so the error message is always true.

Other than that - seems fine..

Nick

**Comment by kslong** [comment] 2020-05-07 14:41
@Higginbottom   I can either make this change or let you do it.  All you need to do is to make the change to the code, and then push it to "origin bug694_dfudge"  If that does not work, then I would like to know.

**Comment by Higginbottom** [comment] 2020-05-07 15:02
So, I have the main repo named as upstream - my local fork is origin.

To look at the code I did

git checkout upstream bug694_dfudge

that gives me a detached head thing that I can edit.

I make the edit then do 

git commit -am "small fix to DFUDGE check in spherical"

then try 

git push upstream bug694_dfudge

and I get

error: src refspec bug694_dfudge does not match any.
error: failed to push some refs to 'https://github.com/agnwinds/python.git'

I don't understand all the complexities of git...

**Comment by jhmatthews** [comment] 2020-05-07 15:08
I think this is because when you do ```git checkout upstream bug694_dfudge``` you are checking out a local version of the branch called upstream/bug694_dfudge - i.e. this is not the same as a local branch called ```bug694_dfudge```, which is what you are trying to push to the upstream remote?

**Comment by Higginbottom** [comment] 2020-05-07 15:11
oh, so the bug694_dfudge in the push command refers to the *local* branch you are pushing? I always assumed it was the name of the branch you were pushing to - and it just pushed whatever local branch you were on.... Hmmmmm...

**Comment by jhmatthews** [comment] 2020-05-07 15:13
Actually, I think that's right and what I said is wrong. Probably a good conversation for slack

**Comment by Higginbottom** [comment] 2020-05-07 15:14
Let me fire it up....

**Comment by kslong** [comment] 2020-05-07 15:33
With the latest merge into dev, this can now be closed.

* Previously, the cell based dfudge was defined explicitly only for cylindrical coordinate systems.  For others is was set to the gloval DFUDGE value.  Now the cell-based dfudge is tuned to the cell size for all  tcoordinate systems a

*  DFUDGE is still used for transfering through the wind, and or hitting the disks.  

* Modifications to DFUDGE in wind_check to reduce the size of DFUDGE, are now just warnings.

**Closed as completed by kslong** 2020-05-07 15:33 UTC
Labels: bug, high
