### ISSUE TITLE
Spectrum normalisation is wrong with restarts with -r flag

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#503] opened 2019-04-16 09:28 UTC
I'm sure we had this exact issue before (see #134). Quite confused as to how it's popped up again.

I was getting confused as to why my macro-atom spectra weren't agreeing anymore, even though they had before I'd restarted. It turned out it was nothing to do with macro-atoms or changes to the code, but because of the restarts with the -r flag. The flux level seems to change in all sources but only in the detailed spectrum. I'm guessing the renormalisation is wrong. It works fine with system type previous. 

I ran this particular test using a non-matom cv_standard model with my kpkt-ff branch but I'm sure it will happen on dev too. This is the Created column of the spectrum file for a few different runs:
![normalisation_test](https://user-images.githubusercontent.com/3007249/56198171-4b54f100-6032-11e9-9d89-d5b522d5a493.png)

**Comment by saultyevil** [comment] 2019-04-17 11:21
James, do you think this will effect runs when restarting from spectral cycles when none have previously been done? For example, I need way more photons in the ionisation cycles, so once those cycles are done I restart Python with less photons for the spectral cycles.

**Comment by jhmatthews** [comment] 2019-04-17 11:52
I'm not sure to be honest, I haven't tested thoroughly- the safest thing to do is probably to use system type previous rather than the -r flag.

**Comment by kslong** [comment] 2019-04-28 18:43
I have confirmed that this problem exists. For some reason, the spectrum produced after restart has a lower normalization than that produced with a full run. 

However, it is  hard to understand what is going wrong.  I ran simple models based on the star.pf model in the regression directory using the a little script where I could vary the number of cycles that were done in the initial and final runs, e. g

py -t 25 star
mv star.sig one_star.sig
mv star.spec one_star.spec
py -r  star

and compared the ratio of the fluxes in the spectra to a  complete run.  What I found was that the ratio of the spectral of the restarted run to a complete run never fell below about 75%, and was lowest when the number of spectral cycles in the intial run was about half of the total.  The normalization was closer to correct if very few spectral cycles were carried out in the initial run, or if nearly all of the spectral cycles were carried out in the initial run.  

Here is the .pf file that I have been using

[star.pf.txt](https://github.com/agnwinds/python/files/3125354/star.pf.txt)

and here is a python script that creates plots and calculates the ratio:

[Debug.py.txt](https://github.com/agnwinds/python/files/3125362/Debug.py.txt)


My guess that this has something to do with the way python is recording cycles.  Previously the cycles were counted from 0 to 14 for a 15 cycle run.  Now they are being printed out at least as 1 to 15.  I have need to check whether this has been done internally to the program, but this is definitely the sort of thing that could create a problem.

I have checked that the correct number of spectral cycles are being calculated in the sense that if the first run above calculates spectral cycles 1-3, then the second run calculates 4-15

**Comment by kslong** [comment] 2019-04-28 20:49
This is the renorm factor in spectrum_restart_renormalize

renorm_factor = ((double) geo.pcycle + 1.0) / ((double) geo.pcycles + 1.0);

This does not look right, particularly the denominator does not look correct since geo.pcycles is the total number of cycles to be run, and not that number -1.  And in fact, it seem likely that the addition of 1 to both of these variables is incorrect since when you read a spectrum file back in the number of spectral cycles will have been incremented to reflect the number completed.

I removed both extra 1's and I put log statements where all of the renormilizations are calculate and got the following:

![screenshot_23](https://user-images.githubusercontent.com/2530901/56869912-04b9ac00-69cd-11e9-8d37-87afb7f52fd3.png)

These look correct to me.  In particular here there were 3 spectral cycles run before the restart, and so at the end of the cycle 2, which is the 3rd cycle one had to renormalize by 5 since there are 15 cycles in total, and then when we restart we renormalize by 0.2  which would seem to restore everything to proper normalization 

... but I note that if I add 1 to the numerator and run exactly the same script it does not seem to have as much affect as I would expect, which is to say that adding 1 back into the numerator only changed the end flux by about 1%, that is the spectrum calculated with a restart had 84% of the flux of the spectrum calculated from all cycles with adding a 1 in the numerator, and 85% with 1 added.  I suspect this is because only the first 3 cycles are only 20% of the total, so that 0.2*1/15 = 0.01 , that is to say I increased the normalization by 1/15 but the changed normalization only affect .2 of the cycles.

Note:  It seems fairly odd to me that we don't simply keep track of the factor by which the spectrum has been renormalized. Why do we need the calculate this on restart? Furthermore, it seems questionable why we renormalize the spectrum internally, we could simply renormalize as we write the spectrum out, and avoid all of this, if indeed this part of the program is the issue.

**Comment by kslong** [comment] 2019-04-28 23:04
@jhmatthews   I have now looked at this problem in some detail.  My conclusion is that renormalization is not needed on restarts, but I would like you to look at this as well.  

What started me down this track was the final note in the previous comment.  In fact, or at least, in what I believe to be correct, we only renormalize what is written out to the ascii spectra; we do not renormalize the spectra internally, and this is what is in spec_save, which is what we read back in.

I am really not sure how to square this with the what is said in #134 but setting the renormalization to 1 solves the problem for the example I have been working with.  

I tried to go back and do an experiment like the one above with the version of python referred to in #134.I checked that we were writing out a spec_save file as we do now, though I did not look in detail if there were differences between this and what we do now.  Unfortunately I could not get this to "restart".  Instead  I got an unknown wind type (2) on restart, which the value for wind_type previous.  

If you have the specific input files you used for diagnosing #134, I am happy to see what happens, but in any event it would be good for you to review all of this, so we can sort out what the correct answer is.

**Comment by jhmatthews** [comment] 2019-05-02 16:49
I'm totally confused by this. 

I ran the  $PYTHON/basic/star.pf model. I tried running it for two ion cycles then two spectral cycles with the dev branch. I then changed the number of spectral cycles to 4, and restarted. I then commented out the call to spectrum_restart_renormalize(), and repeated the whole process.

* When I plot an extracted spectrum (i.e. A45P0.50), it only looks right if spectrum_restart_renormalize is called, which seems contrary to Knox's finding.
* When I plot the Created or Emitted column it is wrong in **both** cases. 

My conclusion is that the fix to #134 does improve something (the normalisation of extracted spectra) but I don't understand why and in any case the "Created" column is wrong in both cases. I don't know why I find different things to Knox. 

Incidentally, I think we do renormalise the spectra internally.

**Comment by kslong** [comment] 2019-05-02 19:28
OK, so James's comments above have clarified a lot for me.   We are dealing with two different scenarios and in once case you should renormalize and in the other one should not.

The restart option was intended for the case where one had placed a time limit on a run, and the model got cut down when the time limit was reached without completing all the spectral desired cycles, and then the program is restarted to complete the run.  

This is different from the case, which James describes above, where the program is allowed to run to completion, the number of spectral cycles is increased, and the program is then program is run with the restart option.

In the detailed spectral cycles, the weight of a photon is set so that at the end of all of the spectral cycles the luminosity of the system will be correct.  If, say, we intended to run 10 spectral cycles, but we stopped the program after one cycle, internally the photons weights would only account for 1/10th of the totally luminosity.  This is why the spectra are multiplied by a factor of 10 when they are written out at the end of the first spectral cycle, by five in the second cycle, 3.33 in the third, etc.  (James - maybe you did not understand what I meant by internally.  What I mean by internally is what are in the spectrum structures)

This is also why for a situation where the run has timed out  (or there was some sort of system crash unrelated to the program) with out completing all the spectral cycles, you do not need to do any renormalization for restarts.  The program really is just continuing.

However, if one runs restart after increasing the spectral cycles on a run which has previously completed, the weights the program will calculate will change, and the internal spectrum from the old run has to be reweighted before continuing.

This explains why James concluded that the spectra needed to renormalized, while I concluded that they did not.

So what should be done?  I definitely want to preserve the case for which restarts was designed, but I can imagine we also want the option of increasing the number of spectral cycles, and not requiring one to use system type previous, which means repeating the spectral cycles.  To do this, we need to sense whether someone has changed the number of spectral cycles between the original run and the restart.  

This ought to be easy though I haven't looked at it.  Before we read in the number of spectral cycles from the .pf file, we store the old value and compare it to the value in the .pf flie for the new run.  If the number has increased we do the renormalization, if it has decreased, we tell the user to think again before continuing.  If it is the same as previously, we continue with out renormalization.

**Comment by kslong** [comment] 2019-05-02 21:42
To check what parameters are read in on restart, I ran a model foo, removed the foo.pf file, and then ran py -r foo.  This shows what parameters are read on a restart, which doesn't really look like the safest thing to be reading in.

[foo.pf.txt](https://github.com/agnwinds/python/files/3140058/foo.pf.txt)

**Comment by jhmatthews** [comment] 2019-05-03 10:30
Ah ok. This is starting to make sense. 

In that case, I think I would probably favour adding code in the function init_photons that checks if pcycles has changed and does something like the following:

```C
  rdint ("Spectrum_cycles", &pcycles);

  if (geo.pcycles > 0 && pcycles != geo.pcycles && pcycles > 0 && restart_stat == RESTART)
  {
    restart_stat = RESTART_CHANGED_PCYCLES;
  }
  geo.pcycles = pcycles;
```

with restart_stat being modified and passed back to the steering routine. The call to spectrum_restart_renormalise is then only carried out if restart_stat == RESTART_CHANGED_PCYCLES. We would then have two other options for restart_stat: RESTART=1 and NEW_RUN=0. 

I'm still a little bit confused as to why the created column and A45P0.50 column can look different.

**Comment by kslong** [comment] 2019-05-03 18:40
James, I believe I have now fixed this problem on the bug503_restart branch, more or less along the lines suggested.  I have tested it for both of the cases described above.  If you have a chance, I would appreciate your trying the test you did previously.  

I have not investigated the question of the difference between the create column and the A45P0.50 column.

**Comment by kslong** [comment] 2019-05-04 14:07
OK, the problem with the created spectra is limited to the case where the number of spectral cycles is increased between runs, as shown in the figure below.  In all cases here, both the 45 deg (first) and created spectrum (second with the same label) are plotted.  

![test](https://user-images.githubusercontent.com/2530901/57180192-ed0a7980-6e4b-11e9-8901-d68d8603970d.png)

My guss is that the spectrum is not being renormalized.

**Comment by kslong** [comment] 2019-05-04 14:29
That was indeed the case.  Only the extracted spectra were being renormalized.  When all the spectra were renormalized, both the created spectra and the 45 degree spectra have the same normalization.  
![test](https://user-images.githubusercontent.com/2530901/57180543-22fd2d00-6e4f-11e9-9718-405ee9207968.png)

**Comment by kslong** [comment] 2019-05-04 14:40
@jhmatthews  I believe the restart issue is completely resolved (including what was happening with the created spectra), and so am closing this issue.  You still may want to check however.

**Closed as completed by kslong** 2019-05-04 14:40 UTC

**Comment by jhmatthews** [comment] 2019-05-04 15:57
Great Knox. Thanks for sorting so quickly. I will double check when I get a minute but I’m sure it’ll be fine.

On 4 May 2019, at 15:40, Knox S. Long <notifications@github.com<mailto:notifications@github.com>> wrote:


@jhmatthews<https://github.com/jhmatthews> I believe the restart issue is completely resolved (including what was happening with the created spectra), and so am closing this issue. You still may want to check however.
