### ISSUE TITLE
Various atomic data files have errors

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#451] opened 2018-11-28 16:25 UTC
In issue  #448 which I plan to shortly close, @jhmatthews  noted that we have various errors being thrown by lines in various atomic datafiles that we are ignoring.  This is dangerous.  Someone needs to review what the errors are and either fix the data files or the code.

This is issue is likely related to several other issues #396 and #195.

**Comment by kslong** [comment] 2018-11-30 23:42
This issue begs the question of what atomic datafiles we want to fix, a point wich @Higginbottom has made in the past.  My guess is what should happen is that we should define a new set to be used, e.g standard82, h10standard82, etc that have error removed and leave the old ones as they are possibly hiding them somewhere so people don't stumble across them.  Comments on this would be appreciated.

Our regression tests generally use standar78, but presumably standard80, the latest non-macro atom  data in that series..  it produces the following errors, on one of the regression test models that I modified to use standard80:

![screenshot_878](https://user-images.githubusercontent.com/2530901/49320295-7517dc00-f4c6-11e8-854e-77b0ff271a95.png)

Note I ran this with the usual -np 3, so there are often 3x as many errors as there really would be with a single thread.

I took the regression tests .pf files and converted all of the standard78's to standard80 and ran a regression test comparing standard78 and standard80.  The output spectra look pretty similar, except at the Lyman edge where for most of the dataset get more Lyman continuum created in emission below 912.  The emitted spectra look quite similar in all cases.

**Comment by kslong** [comment] 2018-12-01 20:43
There is a related issue #156

**Comment by jhmatthews** [comment] 2019-03-22 15:09
Nick, any idea what we need to do here? The errors are quite confusing and we should really get rid of them, but I'm not sure why one ends up with these:

Get_atomic_data: more than one electron yield record for inner_cross
Could not interpret line 126 in file data/atomic80/ver_upsilon_linked.dat
No inner electron yield data for inner cross section

Any ideas what to do @Higginbottom ?

**Comment by kslong** [comment] 2019-03-31 20:36
@Higginbottom @jhmatthews 

These are the current errors associated with Keara's C345 model

[foo.txt](https://github.com/agnwinds/python/files/3027093/foo.txt)

Nick, it would be really helpful if you could comment on them.   As far as I can tell get_atomic_data does not read lines beginning with SCUPS and SCT, which appear to be from (according to the information in get_atomic data) Burgess and Tully 1992.   Does this mean they should be expunged from the data files, or alternatively does it mean we should treat them as comments.  When were they removed from Python?

Someone, remind me also how the inner yield electron data is used?

James, it looks like macro atoms are all marked as topbase, around line 1264.  As, I am sure you know the error about this comes up in checking of the dataset, around line 3263.

**Comment by kslong** [comment] 2019-04-01 16:43
When I looked at this, I could not find where SCT and SCUPS were accessed.  It looked like this was commented out.  Can you enlighten me on where it is?  Knox

**Comment by Higginbottom** [comment] 2019-04-01 17:00
They aren't explicitly referenced, but they are read in on lines 2544 and 2564 of get_atomcdata.c following a match of CSTREN.

Could you add the .pf file in question here so I can get the errors. I don't get them with agn1d.pf for example...

**Comment by Higginbottom** [comment] 2019-04-02 06:33
Hmmmm, just putting that datafile into the cv_standard.pf parameter file causes a segfault crash. Is this something I should open a bug report on - or is it expected coz I’m not doing other macro-file things?

**Comment by Higginbottom** [comment] 2019-04-02 06:58
OK, so I think the reason we are getting the upsilon file errors is because some of the simple lines are ignored in the macro-atom - so the upsilon data isn't matched. It is 
The way ahead depends on what we want. 
First - and this may be needed whatever - is to simply skip over the two 'data' lines in the upsilon data if there is no match for the first line.
Second - I don't know enough about macro-atom data to know if this is right - but we should also search the macro atom line data for matches to the upsilon data.

**Comment by jhmatthews** [comment] 2019-04-02 08:09
Ah, sorry Nick, I hadn't realised that was why. 

I think for the moment, at line 2520 where we loop over lines, there should be a variable that controls whether we found a collision strength or not, and if not we should probably throw an error or log how many collision strengths were ignored if we haven't found one, and if that if statement gets activated we also skip the next two data lines. Agree? 

The second point you raise should definitely happen eventually as Stuart mentioned but I think that might need a bit of work or at least thinking about.

**Comment by Higginbottom** [comment] 2019-04-02 08:57
Thats exactly what I've done! Pull request on its way. 
I was a little flummoxed because there were 77 skipped lines, but 249 errors. One would only expect 77*2 if that was the only issue. The other 77 is because there is no ion data for C1/C2 - surprising but I assume this is correct for the macro treatment. These lines are commented out in data/atomic_macro/CIIICIVCV_c10_elem_ions.py

Now on to the electron yields - lack of matches probably shouldn't be errors but I'm going to check...

**Comment by Higginbottom** [comment] 2019-04-02 09:06
Ooooo, I didn't log it as an error - do you think it should be? I'll wait for KSL to comment too - otherwise I'm just replacing one error with another, albeit more understandable, error...

**Comment by jhmatthews** [comment] 2019-04-02 09:12
Great minds.

My approach with simple lines has been to count how many times it happens and then report it as a single error at the end of data gathering. I can add this in. That way it can be tracked without cluttering.

**Comment by Higginbottom** [comment] 2019-04-02 09:41
Regarding the electron yield - I think that the first error 
get_atomicdata: No inner electron yield data for inner cross section %i %i %i nelec=%I
is real - the list of yields is more restrictive than the list of cross sections. Wehter it should be an error or not is something I'm looking into. e.g. it seems that when there are three electrons in an ion there is no yield data - is this because there is no chance of any more than one electron being spat out when you get an inner shell ionisation - because there will be two electrons after the inner shell one is removed, and presumably the overwhelming likelihood is that the one remaining outer electron drops in and emits a fluorescent photon....

**Comment by Higginbottom** [comment] 2019-04-02 09:52
This looks to be right - the electron yield when there are 4 electrons left is 100% chance of one. so 3 electrons is the same...
This brings up an interesting second point - at the moment - we don't compute matrix elements for inner shell cross sections where we don't have electron yields. So we arent computing them for states with three electrons. I think I'll take a look later at wether this makes any odds to our ionization calculations.

**Comment by jhmatthews** [comment] 2019-04-02 10:02
Ok. I've added a way of tracking the coll strength errors here with a similar thing for the matom line errors: https://github.com/agnwinds/python/commit/70235ec1f9358d781e0e278d384f33fe86b245fb 

Could do a similar thing for the electron yields if you felt it was appropriate.

**Comment by Higginbottom** [comment] 2019-04-02 10:11
Are we both editing at the same time? This is going to get complicated...
And who is aaaaaadam01 - they just commented on the commit....

My current feeling is that when we don't have inner shell yields for a cross section - we should probably create a yield with 100% chance for 1 electron being emitted. This would avoid leaving out inner shell cross sections...
Wether we should log an error is another thing - this is just the data we are using, its not an error. We should probably document the limits of our data, rather than throwing errors every time we hit it!!

**Comment by Higginbottom** [comment] 2019-04-02 10:26
OK, in reply to my own suggestion - we cant do this easily because we need to know the mean energy of the electron emitted by this process, otherwise it will be included in the ionization calls but not in the heating rates. We might be able to work out what the mean energy is - but lets not do that today.

**Comment by Higginbottom** [comment] 2019-04-02 11:02
So the only problem with the method of error logging that just comments once about the number of times something happens, is that you don't get any info at the end. It just says something like:
1 Ignored %d collision strengths with no matching line transition
Ideally we would like it to say how many times this happens, just not spam the screen. 
Error_silent does this.
So, if we don't want to spam, but we do want to know it has happened - Error_silent is the method.
If we don't care, then we should just comment out the error and not care
We could use the method of counting occurrences and reporting it - but this should not be an error, otherwise we still have an error report at the end that might worry people, but there is now no information of how many times it happens, so even advanced users cant tell if it is the 'normal' number of occurrences...

**Comment by jhmatthews** [comment] 2019-04-02 11:08
aaaaaadam01 seems to be a random user who enjoys trying to wind people up, I've reported him. 

I've proposed a way to deal with this via pull request #495 - but I'm also fine with just using Error_silent, it's just that you get a large number of errors, and in this case you only get one per type of data.

**Comment by Higginbottom** [comment] 2019-04-02 11:22
This is stupid, we are both working on the same thing at the same time. 
Either you or I should stop. You have essentially just done all the stuff I did in my branch. But I then deleted it because I don't think this way of doing it is right. 
either we need to know how many times these things happen, in which case we need to use error silent - or we don't in which case there is no point in doing it at all.
There is no point spawning one error, that then doesn't give any information in the error summary!

Lets agree the way forward though, before we just overwrite each others work...

**Comment by Higginbottom** [comment] 2019-04-02 11:25
The 'more than one electron yield' error is a bug.
It is actually referring to fluorescent yields. That aren't used. I'll see if *this* is real, or simply a function of us not knowing what to do with the data yet. If the latter, the fix is to not read in the fluorescent data....

**Comment by Higginbottom** [comment] 2019-04-02 11:36
OK - so we are way off doing fluorescence correctly. I think the best way forwards is to either do it properly - or excise the code.
For the time being - I'm commenting out the fluorescence data file from the data...

**Comment by kslong** [comment] 2019-04-02 13:00
Note:  I do not believe using Error_silent will prevent the errors from being tabulated.  All Error_silent does is avoid sending the error to the screen.

**Comment by Higginbottom** [comment] 2019-04-02 13:06
I agree - I suppose I don't fully understand what the problem is here. Lets try to define it:

For example - the ‘no matching electron yield’ type error is not really an error, it is a result of limitations in the atomic data.

So, there are three iptions”

1: Ignore it completely - just comment out the error - I’m fine with this - but if something else goes wrong that means for some reason *none* of the yields are read in, then we would never know
2: Do what James is suggesting - log the number of occurances and print them to screen with an error - this is to my mind the worst of both worlds - you still get an error, but now it tells you nothing.
3: Do what james is suggesting but just report it as a log - fine - but if there is a problem you have to grip the diag file to get it. - if you dont know there is an issue then you will never know. Still - possibly the best option.
4: Do Error_silent - this is calling something that is not an error an error, but, you avoid screen dumps but still get a count - which can be useful.

To my mind 1/3/4 are all fine…

**Comment by kslong** [comment] 2019-04-02 13:23
Let's clearly state the problem first.  The problem is that we have data files that are incomplete or wrong, and we have not taken this seriously.   We currently dealing with problems in macro atoms that we do not know whether are due to a data file problem or a coding problem, or some combination thereof.  We want to do something to raise our visibility to actual problems, and reduce the amount of stuff we plan to ignore.

If we simply log a problem and nothing more, we are almost saying we will ignore it, because the log files are huge.  The best approach might be to keep counting the errors as we do now, but simply give higher priority to commenting out the bits that are ignored.   The negative of this, is that we are giving up flexibility in the files, which is something get_atomic data was designed to handled.

I guess my take is that the best option of all for the program would be to convert the errors for the line by line problems to Log_silent so they don't appear on the screen and in the error summary, but to count the number of errors of this type that have occurred, and issue a single error at the end of get atomic data for this, e.g "Error: get_atomic_data: %d lines from the data files were ignored in reading the inputs"

However, I think some errors are more serious than others, if there are multiple attempts to read in say a x-section I think that should be logged as an error.

Nick - However you decide to handle all of this.  I think you should create a new issue for any process we have commented out because it was not done properly or finished.  That way we can prioritize when to attack it again.

**Comment by Higginbottom** [comment] 2019-04-02 13:27
But, if you

“issue a single error at the end of get atomic data for this, e.g "Error: get_atomic_data: %d lines from the data files were ignored in reading the inputs”

then you will still get an error report at the end - but you wont know how many times the error happened - unless you grep the diag file for when the error message actually spawned. This is the problem with putting a %d in a call to error - the error summary wont show the number just the %d.

Error silent does exactly the same as log_silent as in it doesnt print to screen, however the error printed at the end is useful…

**Comment by kslong** [comment] 2019-04-02 13:39
Yes, I understand the weakness.  

This however is a generic issue.  We don't give a good summary of how the run went at the end of the log, which is what everyone looks at.   For example, we don't say anything about whether the run converged.  

As you may know, I have written a script run_check.py that I've been showing you all the results of occasionally.   It reads the log file for some of the convergence information.  One possibility is to augment this to pick out errors from the log file that we think are important to note.  The alternative, is to augment the c-routine that runs at the end of the program, and to have this print out the error count itself, or have python call a version of the python script.

**Comment by Higginbottom** [comment] 2019-04-02 13:43
Well, I’ll do it that way - under duress. Seems like the worst of all worlds to me - but since KSL and JM like this method - i’ll do that…

**Comment by Higginbottom** [comment] 2019-04-02 15:07
OK, commented out all the fluorescence stuff - and removed the file reference from the carbon matom and standard80 files.
Also finished James's work turning the errors into one error at the end.
Its just checking for compilation then pull will be complete.
Hope it helps!

**Closed as completed** 2019-06-28 14:17 UTC
