### ISSUE TITLE
segmentation fault in spectral cycles

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#114] opened 2014-09-14 20:10 UTC
Python is now failing, with a segmtation fault,  on a simple spherical polar model (at least on Macs).  The failure is at the generation of detailed spectral files.  The problem is not associated with mpi, as it fails with gcc as well as mpi at the same place, as far as I can tell.

The .pf file sphere_pol.pf is in bug_pf files on Dropbox

**Comment by jhmatthews** [comment] 2014-09-14 20:51
This must be a recent change. I ran the fiducial and CV models in spherical polar just prior to the summer 2014 meeting with good results. 

I think it could be related to the dynamic allocation of memory for the plasma structure. We do a dynamic allocation of the "scatters" member of the plasma structure, which is used when detailed spectra are created, so my guess is that's where it's going wrong. This is almost certainly related to my problems with py_wind which I haven't debugged yet. Making this high priority, as it needs to be sorted for that anyway.

**Comment by jhmatthews** [comment] 2014-09-15 11:09
Hi Knox- this isn't specific to spherical polar, I don't think. I'm able to reproduce the error in cylindrical coordinates, and I think it's caused by this loop added to define_phot

``` C
  for (n=0;n<nphot_tot;n++){
      p[n].w_orig=p[n].w;
  }
```

The problem here is just that the photon structure only ever has size NPHOT i.e. the number of photons per cycle - i.e. it gets repopulated each time. So a simple fix of nphot_tot -> NPHOT here should solve the problem.

**Comment by jhmatthews** [comment] 2014-09-15 11:18
while we're on the topic, why do we do all this stuff in python.c:

``` C
// rddoub ("photons_per_cycle", &photons_per_cycle);
// 140907 - ksl - Although photons_per_cycle is really an integer, read in as a double so it is easier for input
  x=100000;
  rddoub ("photons_per_cycle", &x);
  NPHOT = photons_per_cycle=x;  // For now set NPHOT to be be photons/cycle --> subcycles==1

  photons_per_cycle = (photons_per_cycle / NPHOT) * NPHOT;
  if (photons_per_cycle < NPHOT)
    photons_per_cycle = NPHOT;
  subcycles = photons_per_cycle / NPHOT;
  Log ("Photons_per_cycle adjusted to %d\n", photons_per_cycle);

#ifdef MPI_ON
  Log ("Photons per cycle per MPI task will be %d\n", photons_per_cycle/np_mpi_global);

  NPHOT/=np_mpi_global;
  photons_per_cycle/=np_mpi_global;
#endif
```

It seems to me the variable photons_per_cycle is redundant and can be replaced by NPHOT the global variable in all calls, much the same way we did in #106 . Agreed?

**Comment by jhmatthews** [comment] 2014-09-15 12:05
I'd also be inclined to remove the subcycles variable, or at least clarify why one might want to use it.

**Comment by Higginbottom** [comment] 2014-09-15 17:42
I think the original use of the sub cycles was to reduce the memory requirement of the code. So one split up the phot structure (which can be pretty big) into sub cycles, but could still have gazillions of photons per cycle...
This may well now be redundant....

**Comment by kslong** [comment] 2014-09-16 13:26
Nick is correct that the origin of this was a concern about memory requirements., and I also agree with those who would like to remove this complication.  I suggest someone creating a separate issue regarding this and removing this complication from the code.
Knox

**Comment by jhmatthews** [comment] 2014-09-16 17:03
Will do, closing this discussion.

**Closed as completed** 2014-09-16 17:05 UTC
Labels: high

**Comment by kslong** [comment] 2014-11-16 19:57
I confirmed that the segmentation fault that was occurring no longer occurs.
