### ISSUE TITLE
Dealing with singular rate matrixes with low photon numbers

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#196] opened 2016-02-19 12:08 UTC
At the moment, one of the big problems in the code is when you run a model with not enough photons -- i.e. so some cells get only a few photons in each band -- then the code will probably fall over when it tries to calculate the ionization state. This will happen if you use ionization mode 7 (variable temperature modified saha solver) by producing a load of errors, but in matrix mode it can be a little more spectacular by the matrix being singular when it gets back from GSL, leading to an exit. e.g.

![screenshot 2016-02-19 12 07 08](https://cloud.githubusercontent.com/assets/3007249/13175291/5a567b46-d701-11e5-823e-becec0423b45.png)

What we should really do here, in my opinion, is adopt some kind of approximation if we know this is going to happen. There are a number of approximations one could use and the cell should never matter in the overall spectrum if so few photons are getting to it, but it seems silly to try and solve this rate matrix in these cases. Especially as it's sometimes hard to know how many photons to inject into a model.

**Comment by jhmatthews** [comment] 2018-11-22 12:43
I think this issue can be closed. We have better checks for dealing with singular matrices now and default to not changing the ionization state if there's a major issue. Similarly in macro-atom mode we have more robust sanity checking due to issue #425

**Comment by kslong** [comment] 2018-11-29 18:31
We have encounter another example of this problem in connection with solving #425.  getting Keara's macroatom files to work.  The problem occurred not using one of her sets of macro atom data, but using a parameter file associated with James' quasar model which just has H as a macroatom.

**Comment by kslong** [comment] 2018-11-29 23:22
@jhmatthews @Higginbottom   Here are some updates on the problem we are seeing in the matrix solver.

* The problem is reproducible in the sense that I can restart the .pf file where I see the issue and regenerate the crash
* By turning off the default gsl_error_handler, I have verified the problem is occurring in gsl_linalg_LU_solve (and I can tell you which cell it is occurring in), namely cell 1088.  
* By dumping the matrix that gal_linalg_LU is receiving to a file and then reading back into a Python routine and looking at the matrix, I can see that what is happening is that although  the diagonal elements of the array are all non-zero, they multiply to a number which is vanishingly small.  The matrix is 178 x 178 and multiplying the diagonal and looking at the product as I go along, I see we are at 10**-322 by element 48.  The median of the absolute value of the diagonal elements was 5e-7, the average.
* Oddly, we check with gsl_lininalg_LU_lndet for a determinant issue but our error condition is that this number be 0. I think we made a mistake here.  This returns the log of the absolute value of the determinant, and you do this by taking the log of the diagonal elements and adding them.  This will not generally return 0 even if all the elements are quite small.  
* Their is earlier evidence that cell 1088 was going to be a problem.

![screenshot_875](https://user-images.githubusercontent.com/2530901/49257936-68798200-f3f9-11e8-84d4-c507cae91f79.png)

**Comment by kslong** [comment] 2018-11-30 00:20
I have made a change to our check for of the determinant.  I believe their was an error previously.  Now we bail out if the the results from gsl_lininalg_LU_lndet is less than log(DBL_MIN*10**4).  DBL_MIN is the smallest double one can represent.   

This change has caught the error we were seeing and allowed the program to finish the ionization cycles, but we now fail at the beginning of detailed spectrum generation, with an error saying tha one failed to select a destruction proccess in kpkt.  .... sigh.

![screenshot_877](https://user-images.githubusercontent.com/2530901/49260451-3f5def00-f403-11e8-86fd-d44d584a07b4.png)

**Comment by kslong** [comment] 2018-11-30 04:02
Running the routine from scratch instead of continuing from where we were seems to have solved this problem.  Ideally, though we would perform some sort of check to decide that our "data" are physically reasonable in all instances.  Also, our workaround for the determinant problem leaves the cell in whatever state is was previously, which in the worst case is the initial condition for the cell.

**Comment by jhmatthews** [comment] 2018-11-30 11:10
Hi Knox. The change you've put in looks reasonable - I think it's more conservative than my suggestion of using a copy of the "singular" function from lu.c in gsl, but perhaps that is better.

I suppose it might be worth adding something that reports a "minor error" is this happens in a cell with few photons that has struggled to find a spectral model, and a "major error" if the photon numbers are above some threshold. Either way I'm happy with the general approach and I think we can merge the pull request.

**Comment by jhmatthews** [comment] 2018-11-30 11:21
Actually, I'm not sure it's right. After we call gsl_linalg_LU_decomp (&m.matrix, p, &s) it seems that L and U get stored in m.matrix. So calculating the determinant of m.matrix was never right. Take a three by three matrix. determinant of m.matrix at this stage will be calculating (according to the GSL comments):

```det(m.matrix) = U11 (U22*U33 - U23*L23) - U12 (L21*U33 - U23*L22) + U13 (L21*L23 - U22*L22)```

whereas what we want is det(A) = det(L) * det(U) * some sign (according to wikipedia LU decomp page). det(L) has to be 1, and det(U) is not generally equal to the expression above. So I think we have never ever done this right and we should instead either calculate the determinant of U or check if any of the diagonals of U are zero - since both of these are more efficient than actually calculated det(A).

**Comment by jhmatthews** [comment] 2018-11-30 11:42
I think the best fix is to replace the lndet calculation and error with these lines of code:

```C
  for (mm = 0; mm < nrows; mm++)
    {
      u = gsl_matrix_get (&m.matrix, mm, mm);
      if (u == 0) {
        Error ("Rate Matrix is singular for cell %i with %i photons (%i ionizing) \n", nplasma, plasmamain[nplasma].ntot, plasmamain[nplasma].nioniz);
        return (4);
      }
    }
```

Although i'm not totally sure that passing ints to  gsl_matrix_get is allowed (it expects size_t, so maybe we have to create a new size_t variable to loop over).

**Comment by kslong** [comment] 2018-11-30 14:33
Sigh maybe you you are right.  However,  It says:

unction: int gsl_linalg_LU_decomp (gsl_matrix * A, gsl_permutation * p, int * signum)
Function: int gsl_linalg_complex_LU_decomp (gsl_matrix_complex * A, gsl_permutation * p, int * signum)
These functions factorize the square matrix A into the LU decomposition PA = LU. On output the diagonal and upper triangular part of the input matrix A contain the matrix U. The lower triangular part of the input matrix (excluding the diagonal) contains L. The diagonal elements of L are unity, and are not stored.
The permutation matrix P is encoded in the permutation p on output. The j-th column of the matrix P is given by the k-th column of the identity matrix, where k = p_j the j-th element of the permutation vector. The sign of the permutation is given by signum. It has the value (-1)^n, where n is the number of interchanges in the permutation.

… so I think the diagonal elements multiplied together give you the determinant of U. In practice when this was failing that diagonal was 0.

**Comment by lazygun37** [comment] 2018-11-30 14:47
I’ll be bout 15 min late - please start without me!

Sent from my iPhone

On 30 Nov 2018, at 14:33, Knox S. Long <notifications@github.com<mailto:notifications@github.com>> wrote:

Sigh maybe you you are right. However, It says:

unction: int gsl_linalg_LU_decomp (gsl_matrix * A, gsl_permutation * p, int * signum)
Function: int gsl_linalg_complex_LU_decomp (gsl_matrix_complex * A, gsl_permutation * p, int * signum)
These functions factorize the square matrix A into the LU decomposition PA = LU. On output the diagonal and upper triangular part of the input matrix A contain the matrix U. The lower triangular part of the input matrix (excluding the diagonal) contains L. The diagonal elements of L are unity, and are not stored.
The permutation matrix P is encoded in the permutation p on output. The j-th column of the matrix P is given by the k-th column of the identity matrix, where k = p_j the j-th element of the permutation vector. The sign of the permutation is given by signum. It has the value (-1)^n, where n is the number of interchanges in the permutation.

… so I think the diagonal elements multiplied together give you the determinant of U. In practice when this was failing that diagonal was 0.

**Comment by jhmatthews** [comment] 2018-11-30 17:13
So just to follow up on the telecon, I've checked the method and the code that does it, and in general the diagonals of U do not equal the diagonals of A (although a_11 does equal u_11). So it is possible for one of the diagonals of U to be zero (meaning that A is singular) without any of the diagonals of A being zero - which is I believe what is happening.

**Comment by kslong** [comment] 2018-12-01 04:48
@jhmatthews   I tried the code above, and reran the m16 model.  It did not reveal any examples where u was identically 0.  I believe that at least in solve_matrix what is happening is that when you multiply the trace elements you end up with something that is so close to 0 that the machine cannot handle it, but no single element of the trace is actually 0, so it is the product of the elements in the trace that one needs to check.  Note also that i looked for a situation where the determinant was 0 in the original rate matrix; none of this was identically 0 either, but the determinant there was also very small, but not 0.  If you disagree with this conclusion, the best way forward would be to provide an example.  

Generally speaking, I find whenever the determinate of the original rate matrix is small, then the determinant of the LU decomposition is also very  small, but not identical.  We just need to decide whether we want yo use the determinant original rate matrix or the product of the trace elements of the LU decomposition matrix  Either seems plausible to me.  Let me know which you prefer.

See commit a2931a6158e17b749c72e1b85fe691926d07f514

**Comment by jhmatthews** [comment] 2018-12-01 13:06
In that case Knox, we seem to have a situation where an if statement in a GSL function that asks ```if (u==0)``` is being triggered, but an if statement that asks the same question in matrix_ion.c is not being triggered. The error that's being returned from GSL is not produced by any multiplication (see function singular() in lu.c).

**Comment by kslong** [comment] 2018-12-01 14:35
I do see that, and I see that singular is called a number of times to check what is going on.  However, I am not 100% sure that is what is triggering the errors we were seeing.

I also see that gsl_linalg_LU_lndet, which is a few lines above the singular routine,  just takes the log  of the abs of the trace elements.

**Comment by kslong** [comment] 2018-12-02 18:30
I have implemented changes to matrix_ion to use the errors from gsl_linalg_LU_solve directly.  I've run this on all of the routines which were generating problems to day, namely James' 2016 quasar model, and the two versions of Keara's models.  I am declaring victory for this, @jhmatthews 

These changes have been merged into dev

**Closed as completed by kslong** 2018-12-02 18:30 UTC
Labels: bug, enhancement, high
