### ISSUE TITLE
Error:sobolev:  VERY BAD population inversion in cell 

### ISSUE THREAD

**Issue by guzhiqian** [sirocco-rt/sirocco#689] opened 2020-04-08 08:33 UTC
I meet the Error: sobolev:  VERY BAD population inversion in cell %d: d1 %g d2 %g g1 %g g2  %g freq %g f %g frac_upper %g\n. 
How to solve this issue?

**Comment by kslong** [comment] 2020-04-08 14:10
For anyone to look at this problem, you would need to attach the input file to the issue.  You will either need to add a .txt to the file name or compress it, as github does not accept .pf as a format extension.

**Comment by guzhiqian** [comment] 2020-04-08 23:16
I meet this problem when I set 'Wind.t.init' to a lower temperature, for example as 3000, whilst set both 'Wind.dim.in.x_or_r.direction' and 'Wind.dim.in.z_or_theta.direction' as 30. Additionally, I meet another similar problem that it shows 'sobolev: tau is >1e-3 and nu < gu/gl * nl. Exiting.!!Exit: error codes should be non-zero! ' when I set both 'Wind.dim.in.x_or_r.direction' and 'Wind.dim.in.z_or_theta.direction' lager than 50 whilst set 'Wind.t.init' as 1e5. The attachment is the basic model and just changed some parameters with plausible range in my simulation. 
[reverb.txt](https://github.com/agnwinds/python/files/4453234/reverb.txt)

**Comment by jhmatthews** [comment] 2020-04-09 09:13
Thanks - this is useful testing for us. I think this normally happens because of errors with the population solvers, although I thought we'd sorted out. It might be that choosing low values for t_init creates a specific numerical problem related to the radiation temperature being so different to the initial T_e, but I'm not sure, especially since you get a different error too. 

@kslong we might also want to impose a minimum value on t_init. 3000K is quite low but it's not obvious to the user what to set it to.
 
@guzhiqian could you also post the commit hash of the code you are using? It will be given in the top of the output files, or if you checked out the repository you can do e.g. ```git log``` to see it.

**Comment by kslong** [comment] 2020-04-09 14:38
@jhmatthews   It would be good to understand why the problem occurs, so it does not come back and bite us elsewhere, but if we agree this is just a startup issue and not something that will reoccur then a limit on t_init seems reasonable, as long as we don't end up with a limit on t in subsequent cycles.

**Comment by guzhiqian** [comment] 2020-04-09 17:51
@jhmatthews Git commit hash 88615b7a3149a6310acb2a2f099a4328e80d3cb2,
my simulation often be interrupted by the problem that shows  'sobolev: tau is >1e-3 and nu < gu/gl * nl. Exiting.!!Exit: error codes should be non-zero! ' ultimately, even if it shows 'sobolev: VERY BAD population inversion in cell %d: d1 %g d2 %g g1 %g g2 %g freq %g f %g frac_upper %g\n' caused by the set of low temperature like as 3000k .
![Screenshot from 2020-04-09 07-33-12](https://user-images.githubusercontent.com/61822871/78925247-bdd5a100-7acd-11ea-95ac-b3d690a931ec.png)

**Comment by kslong** [comment] 2020-04-09 22:46
I have had a look at the .pf file, and run various versions of the code.  

I am able to reproduce the error with the .pf file you sent.

I have a number of comments though about this file

- This is a macro atom run using standard80.dat.  This is probably not what you want as this file is intended for non-macro atom runs.  We leave this as an option mainly for diagnostic purposes.
- There is an inordinate amount of energy hitting the disk, more than the total luminosity.  This seems very odd, and might be a bug of some kind.
- The number of photons in each cell was quite small for macro atoms.  Your are running  500,000 per cycle.  A few 1000 was typical for the number of photons passing through an individual cell.  I am not surprised in a way that this is stressing.  With poor statistics, we are likely more susceptible to the problem that causes the program to crash (though @jhmatthews is more of an expert on this than I.)

It is possible to run the model without having it fall over, either if you run it with a more appropriate data file, like data/h10_standard80.dat; it is also possible to run it to conclusion by running it in non macro atom mode, that is with 

Line_transfer  set to   thermal_trapping

This avoids the problem because the portion of the code that fell over is not invoked.  However, we have some reservations about using a simple atom  for AGN models, so I recommend using macro-atoms with the data file I suggested.

As an aside, you probably want to pull the latest version of the data repository.  We did make a change to the file names, if you do this, so .dat is added to the data file names.

**Comment by kslong** [comment] 2020-04-09 22:47
@jhmatthews   Regardless of anything else here, we probably should warn folks about using a simple-atom dataset  in macro-atom model

**Comment by jhmatthews** [comment] 2020-04-27 09:31
Had a look at this. First observation is that the parameter file looks fairly reasonable to me and one that should be able to run, except perhaps for the number of photons, which could cause problems with e.g. the ionization solver. Indeed, the run does produce a lot of errors with spectral estimators and so on.

There appear to be some issues with reporting where luminosity is lost in the system, because the diagnostics don't agree.

Finally, the code seems to fail with the following error: 
```
!!wind_update: Cell 1028 Dom 0  Vol. 2.19e+39 r 0.00e+00 theta 0.00e+00 has only   18 photons
wind_update: Huge w 6.78e+41 in cell 1039 trad   2.96e+04 j 9.34e+54
sobolev: VERY BAD population inversion in cell 1039: d1 1.07447e+11 d2 2.14893e+11 g1 2 g2  4 freq 2.46607e+15 f 0.277 frac_upper 2
sobolev: tau is >1e-3 and nu < gu/gl * nl. Exiting.
```
so I'd guess that the dilution factor (much) larger than one is the root cause of the issue. Looking into it.

**Comment by jhmatthews** [comment] 2020-04-27 10:08
The cell that fails in this case has a large mean intensity but low radiation temperature, which leads to errors as w is so large. I'm not certain, but these cells seem to be embedded somewhat in an optically thick region which is <10,000K and not close to converging. Starting the simulation off with a low temperature might be the fundamental issue but it's hard to figure out exactly what is going on.

**Comment by jhmatthews** [comment] 2020-04-29 09:33
@guzhiqian it seems there are some issues with a re-weighting scheme that the code uses, which is an attempt to have a more realistic treatment of the recombination continuum for "simple-atoms" in an indivisible packet radiative transfer scheme. For the moment, I think the most sensible thing is, as @kslong says, to ensure that you have a hydrogen macro-atom model in the code, by using, for example data/h10_standard80.dat as the atomic data file. You can also try turning off this re-weighting scheme by setting BF_SIMPLE_EMISSIVITY_APPROACH to 0 in python.h, but this is not a particularly realistic treatment of the bound-free continua.

**Comment by kslong** [comment] 2021-05-03 17:48
With the changes that have been made to dev, the problem has disappeared.  Here are the errors that are currently produced

```
        85059 --     8 -- spectral_estimators: too few photons (1 or 0) in cell %d band %d to produce a model
        24296 --     8 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
        22533 --     8 -- rand_wind_thermal_trapping: photon had more than  %d internal scatters in cell %d at %e %e %e with p_norm %e zmin %e tau_min %e
         6468 --     8 -- wind_paths_gen_phot: No path data in cell %d at r=%g, z=%g
          623 --     8 -- spectral_estimators: Alpha cannot be bracketed (%e %e)in band %i cell %i- setting w to zero
           56 --     8 -- getatomic_data: line input f odd (may be OK if Macro): %s
           51 --     8 -- trans_phot: %ld photons were lost due to DFUDGE (%8.4e) pushing them outside of the wind after scatter
           35 --     8 -- error_count: This error will no longer be logged: %s
            8 --     8 -- THIS IS A MACROATOM CALCULATION WITH NO MACROLEVELS
            8 --     8 -- check_grid: velocity changes by >1,000 km/s in %i cells
            8 --     8 -- get_atomicdata: Could not interpret line %d in file %s: %s
            8 --     8 -- Ignored %d inner shell cross sections because no matching yields
            8 --     8 -- get_wind_params: zdom[ndom].rmax = 0 for wind type %d
            8 --     8 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
            8 --     8 -- reverb.type: Wind radiation is off but wind-based path tracking is enabled!
            8 --     8 -- wind2d: Cell %3d (%2d,%2d) in domain %d has %d corners in wind, but zero volume
            3 --     2 -- scatter: kpkt probability (%8.4e) < 0, zeroing
```

While some of these may be worthwhile exploring, this was not the reason this issue was created.  Some of the errors that do appear, would go away if more photons were run.  I am closing this issue.

**Closed as completed by kslong** 2021-05-03 17:48 UTC
Labels: bug, high
