### ISSUE TITLE
Dynamic memory allocation for plasma structure

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#93] opened 2014-07-25 11:39 UTC
With completely filled plasma structures, like zeus files, the memory used by the plasma structure can become significant. 
The size of plasmadummy, with default sizes of NION etc is 53704 bytes. This means, with 8100 cells in the PK04 model, the plasma structure uses 430Mb of RAM, which will also be the size of the wind save file.
One of the main 'wastes' of space is using NION=500, whereas in the runs I've been doing nions=178. 
One can make a big difference by just setting NION to 200 in atomic.h - this almost halves the memory used, but it is hardly a seamless fix for a typical uses.

We might want to consider dynamically allocating the memory, in the same way as the macro structure. Its a low priority, but worth mentioning (I think).

**Comment by jhmatthews** [comment] 2014-07-25 14:57
This seems very sensible to me. I'd suggest any of the arrays which use NIONS or NLTE_LEVELS would be a good place to start with dynamic allocation.

**Comment by kslong** [comment] 2014-07-27 14:29
This also seems sensible to me, though I remember thinking about some of this in the dark past.  I do not believe you can dynamically allocate arrays within a structure.  Therefore, what you have to do is pull the current array out of the structure and at which point you can dynamically allocate the “current array”.  You then have to use pointers to point from the current structure to the new arrays.  This can be confusing.  The macro atom structures, as we increase the numbers of atoms we use may also cause space problems.

Right now, I recommend setting the sizes in the .h files to the maximum values in any of our data files.  Presumable, if we create a new set of data files and then try to read them in, python will throw an error and we can just recompile.

Cheers,
Knox

**Comment by jhmatthews** [comment] 2014-07-28 12:43
Knox- we do this already in the macro atom structures, and it's not particularly confusing. One just declares the array in the structure as e.g.

``` C
typedef struct plasma
{
  double *array;
  ...
} plasma_dummy, *PlasmaPtr;
```

And then you need 1 calloc statement for the structure and N for however many arrays you have e.g.

``` C
plasmamain = (PlasmaPtr) calloc (sizeof (plasma_dummy), (nelem + 1));
for (n = 0; n < nelem; n++)
  {
    plasmamain[n].array = calloc (sizeof (double), size_array);
    ...
  }
```

where size_array would be the actual nions, for example. I say we do this

**Comment by kslong** [comment] 2014-07-30 14:10
Agreed.  Knox

**Comment by Higginbottom** [comment] 2014-07-30 21:13
I've implemented dynamic arrays for the 12 variables with length NIONS. Testing what I've done, but looking OK. I'll look to see what can be gained from doing the same for the NLEVEL length variables.

Should doing a pull request for this tomorrow..

**Comment by kslong** [comment] 2014-09-05 21:38
I am re-opening this issue, until it is better tested.
Let's debug this problem here

**Comment by jhmatthews** [comment] 2014-09-30 12:48
@kslong - I haven't been able to reproduce the error I thought this had caused, so I think this was an error on my part. I'm closing this, but will reopen if anything related comes up. I've rechecked the code and it looks fine.

**Comment by jhmatthews** [comment] 2014-10-03 11:57
Now I have reproduced an error- running 1d_sn.pf, or in fact any model which uses the standard_sn_kurucz. I get a segmentation fault in the lucy mazzali portion of the code for calculating ionization balance.

I am able to remove the segfault by the following methods:
- decreasing the abundances to less than the large SN abundances for metals to more 'solar like' values
- replacing the dynamic allocation of the density array with the old method using density[NIONS]
- replacing the newden allocation in the lucy() function with a dynamic allocation 

It's not yet obvious to me why this happens because I can't figure out why these things work. While I can make the error go away, I don't consider this to be a fix to the problem until I understand why.

**Comment by jhmatthews** [comment] 2014-10-14 16:47
Just to recap the actual error:

running ~/Dropbox/Python/bug_pf_files/1d_sn_segfault.pf with the latest dev version should cause a segfault after the first cycle, in the ionization routines.

This uses standard_sn_kurucz atomic data which is already in the data repository.

I get this output:

```
error_count: This error will no longer be logged: lucy_mazzali1: fudge>10 www %8.2e t_e %8.2e  t_r %8.2e 

nebular_concentrations: failed to converge:nh 1.00e-20 www 1.00e-20 t_e 9.13e+03  t_r 1.11e+04 
ionization_on_the_spot: nebular_concentrations failed to converge
ionization_on_the_spot: j 1.15e+11 t_e 9.13e+03 t_r 4.15e-01 w 1.00e+01 nphot 30453
[cosmos:11990] *** Process received signal ***
[cosmos:11990] Signal: Segmentation fault: 11 (11)
[cosmos:11990] Signal code:  (0)
[cosmos:11990] Failing at address: 0x0
[cosmos:11990] [ 0] 2   libsystem_c.dylib                   0x00007fff90b5d8ea _sigtramp + 26
[cosmos:11990] [ 1] 3   libsystem_notify.dylib              0x00007fff97196000 __dso_handle + 0
[cosmos:11990] *** End of error message ***
Segmentation fault: 11
```

and in the debugger it looked like it was failing in line 834 of saha.c in the lucy_mazzali function.

**Comment by kslong** [comment] 2014-10-15 17:01
This is failing in these lines of lucy_mazzalit:

``` C
  while (density[last - 1] < 1.1 * DENSITY_MIN)
    {
      newden[last - 1] = DENSITY_MIN;
      last--;
    }
```

For the 1d .pf file, the densities are small for whatever reason and so this loop keeps decrementing last until it gets to be less than 0.  This produces a segmentation fault, as one might expect.

So, first of all we can trivially fix this problem by preventing this (and the loop above) to exceed the limits of the density array.   

However, we might want to understand why the densities are so low for this particular model.

**Comment by jhmatthews** [comment] 2014-11-05 19:05
This is fixed in commit https://github.com/agnwinds/python/commit/dae9d5b58db0bad10820c8ef83cc2f13df4c86a6

with the following code:

``` C
  /* JM 1411 -- we only want to increment first if 
     we don't go off the end of the array, see #93 */
  while (density[first] < 1.1 * DENSITY_MIN && first < last)
    {
      newden[first] = DENSITY_MIN;

      first++;

      /* if first has been incremented all the way up to last 
         then this means all ions have negligible densities - 
         so throw an error */
      if (first == last)
        Error("lucy_mazzali1: elem %i has all ions < %8.4e density\n", 
               nelem, DENSITY_MIN);

    }

  /* JM 1411 -- we only want to decrement last if 
     we don't go off the end of the array, see #93 */ 
  while (density[last - 1] < 1.1 * DENSITY_MIN && last > first)
    {
      newden[last - 1] = DENSITY_MIN;

      if (last > first)
        last--;
    }
```

If you ever have a situation where first == last then this means you have every ion in that element with very low densities.

This should never really happen- the reason it does in this model is I had included Hydrogen with a very low abundance. Closing this issue.

**Closed as completed by jhmatthews** 2014-11-05 19:05 UTC
Labels: enhancement, low
