### ISSUE TITLE
Variable Name Consistency

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#530] opened 2019-06-17 15:41 UTC
Some variables are inconsistently named and could do with being renamed.

* `lum_agn`: This probably belongs to BH/AGN. `BH.luminosity`?
* `low_energy_break`:  This is associated with banded photon sampling. `Photon_sampling.low_energy_break` or `Photon_sampling.user.energy_break.low`
* `high_energy_break`: As above
* `wind.fixed_concentrations_file`: This is associated with the `Wind_ionisation` settings, so should be `Wind_ionisation.fixed_concentrations_file`

**Comment by kslong** [comment] 2019-06-19 20:48
Regarding the comment on #519, I definitely believe we ought to capitalize Wind, but I think I would prefer Wind.fixed_ionization_file.  Several of the parameters associated with Wind, e.g Wind_heating, night also start Wind.  The only philosophical questions is should we have the items that are global and apply to all domains, like ionization in a separate group of variables

**Comment by kslong** [comment] 2019-06-29 15:21
@smangham I am still confused why Wind.fixed)ionization_file or wind.fixed_ionization_file is a problem that is causing me not to be able to merge because something is happening with ../docs/rst/parameters/Wind.autogen.rst.   While I do think we should standardize our names properly, I don;t think it should be enforced by something so deep within the code.    A nice warning would be acceptable.  Can you tell me what is the underlying problem here.

**Comment by smangham** [comment] 2019-07-02 10:45
The underlying problem is that we generate a single parameters file for each root parameter type (e.g. `Wind.autogen.rst` for `Wind.mdot`, `Wind.radmax`, `BH.autogen.rst` for `BH.luminosity`). However if there's both `wind.blah` and `Wind.blah` parameters, because they're different strings it'll create a `wind.autogen.rst` and `Wind.autogen.rst` file. 

We could add a small UUID or hash to the filenames to prevent collisions (e.g. `wind.34ab34f.rst`), but as filenames become the URL, that would make the page URLs a bit awkward and inconsistent.

I certainly agree there should be a warning, and the `autogen` script for the documentation should tell you if there's a filename collision. I think refusing to generate documentation that would result in filename collisions and informing the user they need to correct the filenames would be preferable to generating files with awkward filename?

**Comment by smangham** [comment] 2019-07-02 14:25
Provisionally, `autogen_parameter_docs` will output this:
    
    ERROR: There are parameter roots that only differ by case!
    - Diag and diag: diag.save_photons
    Cannot write documentation as it will not work in case-insensitive OSes (e.g. Mac, Windows)

**Comment by smangham** [comment] 2019-07-10 10:15
* `AGN.power_law_index` is a version of `BH.power_law_index` that is only called for boundary-layer emission (i.e. non-AGN systems).
* `AGN.power_law_cutoff` is likewise related to `BH.power_law_cutoff`.

Functionally, the `BH.` and `AGN.` and `BL.` options are all referring to the same things. We have separate machinery for when `geo.agn_radiation=1` and `geo.bl_radiation=1`, but there is no case in which both can be true, and they both just call `photo_gen_star` passing their global radiation types to it. So functionally, we can collapse the two together eventually, as long as we can solve the issue with stars wanting thermal radiation and a boundary layer.

The short-term solution is to rename them all to `Central_object.thing` and build up some technical debt.

**Comment by smangham** [comment] 2019-07-10 11:20
So in a `System_type star` model, we already use `Central_object.radiation`, `temp` and `rad_type_to_make_wind`/`spectra` for the star. So actually all the `AGN.thing` stuff will be renamed to `Boundary_layer.thing` and all the `BH.thing` will be renamed to `Central_object.thing`.

**Comment by kslong** [comment] 2019-07-16 21:29
@saultyevil  There is an underlying issue with all of this.  CV systems, which typically have radiation from a star and a boundary layer, and we have X-ray binaries and AGN, which have radiation from a central BH.    Right now, we capture the radiation from stars, with parameters that begin with Central_object, and the radiation from BHs and boundary layer with parameters that begin with BH.  

What ties Boundary Layers and BHs together is that the same types of spectra are applicable to all of them, and also typically that we need to wait until we know about the disk accretion rate before we can suggest default values for the luminosity of what every type of spectrum is involved.  

The current beginning part of an AGN model is

```
System_type(star,cv,bh,agn,previous)                  agn

### Parameters for the Central Object
Central_object.mass(msol)                     1e+09
Central_object.radius(cm)               8.85667e+14

### Parameters for the Disk (if there is one)
Disk.type(none,flat,vertically.extended)                 flat
Disk.radiation(yes,no)                          yes
Disk.rad_type_to_make_wind(bb,models)                   bb
Disk.temperature.profile(standard,readin)             standard
Disk.mdot(msol/yr)                               1
Disk.radmax(cm)                         8.85667e+16

### Parameters for BL or AGN
BH.radiation(yes,no)                            yes
BH.rad_type_to_make_wind(bb,models,power,cloudy,brems)                power
BH.lum(ergs/s)                          4.72063e+45
BH.power_law_index                             -1.5
BH.geometry_for_pl_source(sphere,lamp_post)               sphere
```

and for a CV model is

```
System_type(star,cv,bh,agn,previous)                   cv

### Parameters for the Central Object
Central_object.mass(msol)                       0.8
Central_object.radius(cm)               7.25182e+08
Central_object.radiation(yes,no)                  yes
Central_object.rad_type_to_make_wind(bb,models)                   bb
Central_object.temp                           40000
Binary.mass_sec(msol)                           0.4
Binary.period(hr)                               3.2

### Parameters for the Disk (if there is one)
Disk.type(none,flat,vertically.extended)                 flat
Disk.radiation(yes,no)                          yes
Disk.rad_type_to_make_wind(bb,models)                   bb
Disk.temperature.profile(standard,readin)             standard
Disk.mdot(msol/yr)                            1e-08
Disk.radmax(cm)                          3.2151e+10

### Parameters for BL or AGN
Boundary_layer.radiation(yes,no)                  yes
Boundary_layer.rad_type_to_make_wind(bb,models,power)                   bb
Boundary_layer.luminosity(ergs/s)          4.61226e+34
Boundary_layer.temp(K)                       100000
```
which does not look too bad.  

I'm not sure, pushing more of the variables to be Central_object.thing would really be an improvement.  What do you think?  @jhmatthews  you should feel free to chime in as well.

**Comment by kslong** [comment] 2019-07-16 22:07
Problems do remain however if you try to create a power law model for the boundary layer of a CV, as shown below:

```
System_type(star,cv,bh,agn,previous)                   cv

### Parameters for the Central Object
Central_object.mass(msol)                       0.8
Central_object.radius(cm)               7.25182e+08
Central_object.radiation(yes,no)                  yes
Central_object.rad_type_to_make_wind(bb,models)                   bb
Central_object.temp                           40000
Binary.mass_sec(msol)                           0.4
Binary.period(hr)                               3.2

### Parameters for the Disk (if there is one)
Disk.type(none,flat,vertically.extended)                 flat
Disk.radiation(yes,no)                          yes
Disk.rad_type_to_make_wind(bb,models)                   bb
Disk.temperature.profile(standard,readin)             standard
Disk.mdot(msol/yr)                            1e-08
Disk.radmax(cm)                          3.2151e+10

### Parameters for BL or AGN
Boundary_layer.radiation(yes,no)                  yes
Boundary_layer.rad_type_to_make_wind(bb,models,power)                power
lum_agn(ergs/s)                         4.61226e+34
AGN.power_law_index                            -1.5

```

**Comment by kslong** [comment] 2019-07-16 22:37
The particular issue described in the previous comment, the last two lines of the .pf file above, is now fixed.

**Comment by kslong** [comment] 2019-07-17 14:04
I was hoping we would work a little more incrementally, as the fact that the keywords had not been updated was holding me up.  But I will push a small change to dev to add some synonyms, and leave this alone area alone for today.

So if you can pull, merge and push back, that would be great.   I do think you need to fix the keywords, at least in the regression and travis directories though.

Or if that is not possible for you let me know, and I will do the BH --> Central_object switch, as this is very easy.  In that case, you will still need to do a pull, merge and push back to make sure we are still on the same page.

**Closed as completed** 2019-08-12 09:43 UTC
Labels: Release
