### ISSUE TITLE
Convert from using local GSL install to relying on system install.

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#587] opened 2019-08-12 15:44 UTC
This will require:
- Editing the README and installation instructions
- Editing the library paths in the makefile

**Comment by kslong** [comment] 2019-08-12 21:23
There are at least two additional things this will require

- Verifying that travis will still run
- Removing the gsl libraries from the repository

**Comment by smangham** [comment] 2019-08-19 10:40
Annoyingly, the `libgsl-dev` package on `apt` only goes to GSL v2.4, whilst Romberg integration seems to only be added in v2.5. So we're going to have to specify the users must do a manual install, rather than using `apt`. I'll check tomorrow whether we can use the homebrew version on Mac.

**Comment by saultyevil** [comment] 2019-08-19 12:47
It looks like we should be fine for installing via Homebrew as the [formulae page](https://formulae.brew.sh/formula/gsl) for GSL indicates that it is version 2.5. It looks like [MacPorts](https://www.macports.org/ports.php?by=library&substr=gsl) also has version 2.5 available.

**Comment by smangham** [comment] 2019-08-19 16:18
Well, it's running bar the Balmer Test stuff. That's still breaking as it's python 2. Deprioritised though.

**Comment by kslong** [comment] 2019-10-10 18:53
@Higginbottom @smangham   I checked our old gsl 1.1.15 and C is defined there as well in gsl_cblas.h.  It is defined as part of a prototoype.  That also seems to be the case in gsl2.5.  So I do not understand how this could be causing a problem.  I still want to understand what it is.  Sam, can you say exactly what gsl version you have been using and I will attempt a fresh install to see if I can reproduce the error.

**Comment by smangham** [comment] 2019-10-28 13:01
We have closed this. Updated to local GSL 2.6, removed complicated workarounds.

**Comment by kslong** [comment] 2019-10-28 21:18
It is too early to close this issue, as we have not really checked it yet.

**Comment by kslong** [comment] 2019-10-28 21:24
Installed over my existing version on my laptop.  Ran .configure, make install, and then make all.
Also confirmed, I could install it from scratch.

@smangham  This branch contains lines that were not indented properly.  Please fix, so we can properly "blame" the right person for changes.

The next obvious step is to see if we can go back to earlier version.  The answer to this is NO. We run into various problems with C, etc.  Evidently now ./configure, etc. at a minimum now to go back to earlier versions.  Not a killer, but needs at a minimum documentation.

**Comment by kslong** [comment] 2019-10-28 21:43
Good news in a sense @smangham   With this new version of dev, I have been finally able to reproduce the issue with having constants named C, which is something I never was able to do previously.    

The real problem was not that we have a #define setting C to the speed of light but  that in various places we were including atomic.h before the gsl headers.  As a result, the #define comes along and redefines the definition of C in the gsl headers.  What we should have done and should do, is make sure the the gsl headers appear before atomic. h. 

For example, one of the places we were seeing the problem was in bb.c.  You get an error compiling an older version of pyhthon in bb.c.  If you change the order of the includes to

```
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>
#include "atomic.h"
#include "python.h"
```
bb.c compiles just fine.  Even if we keep VLIGHT, etc. this is a problem that should be fixed.

**Comment by kslong** [comment] 2019-10-28 22:05
As @smangham you probably already knew, you do have to go back and do a .configure, etc, to go back to an earlier version.  To me this implies, we need to change the version number right now, possible all the way to 84 to align with the gsl change.  

On the other hand, you can use an old version of gsl and just switch back to dev, without the reconfigure step.  I am not sure this is a good thing.  It suggests, that we may need to record the gal version just as we do the commit version.  

Note that I now have both
```
./software/gsl-2.5/bin/gsl-config
./software/gsl-2.6/bin/gsl-config
```
which may mean that there is a way to make sure to check that we have the correct version of the gsl software for each version.  Perhaps the Makefile can check ... at least going foward.

**Comment by kslong** [comment] 2019-11-02 22:06
@smangham   With our new installation, if you go to a version of python that predated the latest changes related to gsl, one has to run .configure again and recompile the old version of gsl.  Is there a way to avoid this?  This did not happen in the summer when I switched versions so I think it is something to do with our "new" approach.

I can use the old version of gsl with the new code

**Comment by kslong** [comment] 2019-11-03 16:36
I worked on this question a bit more.  I think the anwer is that it is not unfortunately not possible to use the old new version of gsl with the old code.

One can modify the headers in our current gsl to eliminate conflicts with things like #define C, and in fact this is easy to do, and I tested this.  All you need to do is change the function definitions in linalg.h to something other than C, e.g. to CC.  We would have to put this in our version of gsl on the Python repository.  

But this does not eliminate conflicts between my_linalg.h (which is part of the old versions of python) and various gsl definitions. You get errors saying you are redefining various things.   Getting rid of my_linalg.h before compiling does not work, so it seems you would have do something more complicated.

So, I guess we are stuck, when we want to compare results pre gsl 2.6 whatever, to those after gsl 2.6, to issuing .configure and make install again.

**Comment by kslong** [comment] 2020-04-23 21:04
We have demonstrated that upgrading versions of gsl can cause us to have to do work modifying python, and not keeping gsl with Python means that old versions of the Python code may not work.   Therefore, I propose we keep with our current approach which is to keep gsl part of the the Python repository.  I am closing the issue; if others disagree they should reopen it.

**Closed as completed by kslong** 2020-04-23 21:04 UTC
Labels: admin, documentation, Release
