### ISSUE TITLE
Rtheta import

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#695] opened 2020-04-24 12:25 UTC
Trying to make a thin shell, gridded in theta direction.

This model file is intended to make a one cell thick x 8 cell in the radial direction...

[model.txt](https://github.com/agnwinds/python/files/4528748/model.txt)

It is run in this parameter file

[shell2.pf.txt](https://github.com/agnwinds/python/files/4528752/shell2.pf.txt)

Run using this commit: 508233cc934c40f3cee275a44e3e50b851e6374a

it makes 8 real cells, the output of py_wind nphot option:

z/theta \x/r-1.75e+08 -1.75e+09 -1.75e+09 -3.49e+09 
1.00e+10        0        0        0        0 
1.00e+10        0  1.9e+03        0        0 
9.81e+09        0  5.8e+03        0        0 
9.24e+09        0  9.3e+03        0        0 
8.31e+09        0  1.2e+04        0        0 
7.07e+09        0  1.5e+04        0        0 
5.56e+09        0  1.7e+04        0        0 
3.83e+09        0  1.9e+04        0        0 
1.95e+09        0  1.9e+04        0        0 
6.12e-07        0        0        0        0 
6.12e-07        0        0        0        0 

now using the current commit: a59922445f878a1ffe0bbc262432b09c54e2dde9

the same file gives

 Nphot tot per cell 
z/theta \x/r-1.75e+08 -1.75e+09 -1.75e+09 -3.49e+09 
1.00e+10        0        0        0        0 
1.00e+10        0        0        0        0 
9.81e+09        0  3.2e+03        0        0 
9.24e+09        0  9.3e+03        0        0 
8.31e+09        0  1.2e+04        0        0 
7.07e+09        0  1.5e+04        0        0 
5.56e+09        0  1.1e+04        0        0 
3.83e+09        0        0        0        0 
1.95e+09        0        0        0        0 
6.12e-07        0        0        0        0 
6.12e-07        0        0        0        0 

two extra ghost cells....
Now implementing a suggestion that ed sent so this issue might get closed fast!!!

**Comment by saultyevil** [comment] 2020-04-24 12:27
@Higginbottom I found another typo... I've just pushed the changes to the bug686 branch. Could you try that out?

**Comment by Higginbottom** [comment] 2020-04-24 12:40
Still the same behaviour… I’ve put up a bug report..

**Comment by saultyevil** [comment] 2020-04-24 13:11
So the problem is that geo.rmax is too small. In parameter file, geo.rmax = Wind.radmax = 1e14cm. 

In the old and new versions of the code, rmax, zmax, etc. are set to 1e11. So thankfully they both agree there.

![Screenshot_20200424_140402](https://user-images.githubusercontent.com/19627279/80215493-7524f880-8634-11ea-9f42-4004d86488b7.png)

Both code versions are also in agreement too with what cells are marked as inwind and not inwind, so there isn't a problem related to reading in and assigning cells. 

Where they disagree is the value of geo.rmax before photon transport. This confuses me since we do `zdom[ndom].rmax = rmax;` in both versions. The difference is that in the old version of the code, somewhere the Wind.radmax value which is read in from the parameter files overwrites the rmax value determined by the imported wind - even though we do this after setting rmax to Wind.radmax.

I'm going to track all the changes to zdom.rmax and geo.rmax to see what's going on.

**Comment by saultyevil** [comment] 2020-04-24 13:52
Okay, I'm an idiot. The error was caused by using degrees in sin() and cos() instead of radians.

Using radians gives,

```
 Nphot tot per cell 
z/theta \x/r-1.75e+08 -1.75e+09 -1.75e+09 -3.49e+09 
1.00e+10        0        0        0        0 
1.00e+10        0  1.9e+03        0        0 
9.81e+09        0  5.8e+03        0        0 
9.24e+09        0  9.3e+03        0        0 
8.31e+09        0  1.2e+04        0        0 
7.07e+09        0  1.5e+04        0        0 
5.56e+09        0  1.7e+04        0        0 
3.83e+09        0  1.9e+04        0        0 
1.95e+09        0  1.9e+04        0        0 
6.12e-07        0        0        0        0 
6.12e-07        0        0        0        0 
``` 

As it should be. Fixing now!

**Comment by Higginbottom** [comment] 2020-04-24 13:56
Where is that - was just pottering through import_rtheta_setup_boundaries which seemed OK..

**Comment by saultyevil** [comment] 2020-04-24 13:58
In the structure `imported_model[ndom].theta[n]`... the values in theta are still in degrees, so doing ` sin (imported_model[ndom].theta[n_outer] / RADIAN)` instead fixes the problem

**Comment by Higginbottom** [comment] 2020-04-24 14:07
Aaaaaahhhhhh.. It is odd that we mainly use degrees in python structures and variables. Easy to be caught out..

**Comment by saultyevil** [comment] 2020-04-24 14:15
Can you double check on your end that the problem hasbeen fixed? If it is, I'll merge in the changes to dev and we can close the issue.

**Comment by Higginbottom** [comment] 2020-04-24 14:29
That looks good!

N

**Comment by saultyevil** [comment] 2020-04-24 15:11
We can close this issue now. Pull Request #696 has been merged in to address this issue!

**Closed as completed by saultyevil** 2020-04-24 15:11 UTC
