### ISSUE TITLE
Incorrect polodial velocities in SV models at the edge of the wind; the general issue of partial cells

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#900] opened 2021-08-27 15:30 UTC
It's that polodial velcoties are not being calculated correctly for partially in-wind cells. Below is a plot of the polodial velocity (which I've calculated, it's not saved in the wind_save file). Along the bottom of the wind, the polodial velocity is decreasing  with radius for the strip of partially in-wind cells. This shouldn't happen and looks to be causing an enhanced region of H I which (probably) isn't real. 

Here is a parameter file which shows this error: [tde_opt_cmf.pf](https://github.com/agnwinds/python/files/7067900/tde_opt_cmf.pf.txt). 

![](https://user-images.githubusercontent.com/19627279/131147712-2e749797-a5c2-409f-8bc8-869a55486dbc.png)

And here is the corresponding mass density, which also looks wrong:

![image](https://user-images.githubusercontent.com/19627279/131151131-b189c10f-e8af-4ca4-8eed-0fe72dbc3cd5.png)

This model uses a lambda = -2 for the mass loss, and a grid resolution of 100x100 cells of which only 2072 cells are actually in-wind. Potentially, this could be a gridding issue.

**Comment by kslong** [comment] 2021-08-30 19:09
I agree that the results look a bit odd.  You can get a better idea of what is happening though by creating a column in the master table for v_pol which you have done and then using plot_wind.py, with the following call from a Jupyter script or something similar

plot_wind.doit('foo.txt','v_pol',inwind='all')

This produces something like:

![foo_log_v_pol](https://user-images.githubusercontent.com/2530901/131390942-845c534a-453a-4ff1-9f1d-d7b8a2188a1b.png)

If you look in sv.c, in sv_find_rho_zero, you will see that there is a rather odd way of extrapolating when we are inside or outside the wind cone that is probably not what one wants.  This is what needs to be investigated and fixed.  Note that one needs to be careful to prevent the total velocity from being greater than the speed of light.

**Comment by saultyevil** [comment] 2021-11-20 20:28
I've attached a recent parameter file which shows the error still (the fiducial model in my latest paper). When you look at the wind, you will see that the partially in wind cells on either edge of the wind are noticeably different to the fully in wind cells, especially at large radii.

When you run this model (which takes about 15 hours with 200 cores using -p 2), the partial cells at large radii have abnormally large densities, an enhanced H I population, and the electron temperature is lower than the surrounding cells. This, I think, is caused by incorrect poloidal velocities as described in the first post.

The files for the model are available on [OneDrive](https://1drv.ms/u/s!AkpPf6fSLA5DiLxSTt8pGPg1zBxS7g?e=x9GG5y), with the root tde_opt. And here is the parameter file, anyway.

[tde_opt.txt](https://github.com/agnwinds/python/files/7575173/tde_opt.txt)

**Comment by kslong** [comment] 2021-11-26 20:20
In the branch bug900_vel, I have made changes intended to extrapolate the SV model along the lines that Christian and I have been discussing.  These produce a smooth variation in theta and a smooth variation in the poloidal distance as a function of rho at a fixed z height above the disk.   However, there still are sharp changes in the velocities at innner boundary of the wind, as indicated below.   Although the new version of the code is better in the sense that we do calculate velocities everywhere, it is not obvious that it helps right at the edges.

![theta](https://user-images.githubusercontent.com/2530901/143626612-029d02d1-b9fc-49c4-9b98-6272e07aff6a.png)

![ldist](https://user-images.githubusercontent.com/2530901/143626622-3140acb3-d99d-4ac2-9844-b9f9829bc9a6.png)




![velocities](https://user-images.githubusercontent.com/2530901/143627811-55e7c518-6ac9-40c7-bd77-d3e2aad2256f.png)

![rzero](https://user-images.githubusercontent.com/2530901/143626635-23a5baf3-9728-4a4d-81d6-e5d1e2b21e1a.png)


![foo_log_v_pol](https://user-images.githubusercontent.com/2530901/143629630-5758500e-f56d-4adc-aaa2-c2594afa0e9a.png)

**Comment by kslong** [comment] 2021-12-07 14:07
Christian and I have explored this problem in a fair amount of detailed, and some changes have  been made to the code.  
The problem here is how to extend the velocity field of the SV model to all of the vertices of a cell which is partially in the wind.

We have explored doing this by modifying the relationship for theta as a function of r_o inside of the inner winner cone. theta inside the wind is defined by the variable

x=(r_o-r_min)/(r_max-r_rmin) 

which is 0 when r_o=r_min.  For gamma of 1, there is an simple extension of the model, simply letting x be less than 0 works for ways inside of the wind.  

The problem is that this extension only works for a small distance inside the wind, and if this distance is too small then it does not cover all of the vertices of a cell that is partially in the wind.

The distance inside the windcone that can be covered depends on the specific model.  Unfortunately the distance covered is generally a fairly small multiple of the distance from the origin to inner wind cone at the base of the wind.  Since the scale of the wind is generally orders of magnitude larger than this, there is no guarantee that one will cover all of the corners of every grid cell that is partially in the wind.

The figure below illustrates the problem.  For the TDE model is shows how the polar velocity as a function of distance from the z axis at a z_height of 1.5e15.   Note that the dotted lines in the figure indicate the position of the the inner and outer wind streamlines at this z_height.

![tde_opt_cmf v](https://user-images.githubusercontent.com/2530901/145043701-27ebd53e-a00f-4e65-9653-c33c51371878.png)

**Comment by kslong** [comment] 2021-12-21 23:39
As discussed in issue #930, our attempts to extend the wind outside the wind cone resulted in very times to initialze the wind due to problems finding the footpoint outsde the windcones, or more probably jsut inside the inner windcone.  The last attempt to do this is in commit 40405366db19d62cfd4cc118f71cd6ab0dc4a5cb

Since we have made a command decision, at least for now to ignore cells that are partially in the wind, this version of dev reverts to our old treatment of the sv model outside the windcones
 
 394ae05ea3433ff9278db58be634d8019bef09fc

Before this issue is closed, we need to make sure that all this is documented, and that partially in the wind cells are truly ignored.

**Comment by kslong** [comment] 2022-01-20 20:03
We do not plan any further work on this issue and I am going to close it.  The way things have been left is as follows

* The default in py86a is to ignore partial cells.  There are two methods for ignoring that can be invoked.  In the default method we simply set the densities of partial cells to zero.  A method which is more analogous to how edges of the wind are treated in the past is available with the appropriate diagnostic switches.
* The sv models have not been modified from what they have been historically.  There are ways to extend them for a short distance in the case that gamma is 1, but the utility of these methods depends in detail on the exact sv model being used.

An alternative for dealing with partial cells which would be to calculate a velocity that is actually in the wind, though discussed has not been implemented.

There are additional issues regarding partial cells, which might be more important

- Does including partial cells, which are small compared to adjacent, cells that are in the wind cause convergence problems?
- Would we be better off not interpolating densities at all?

**Closed as completed by kslong** 2022-01-20 20:03 UTC
