### ISSUE TITLE
Generic problems with enums

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#162] opened 2015-08-05 16:39 UTC
Original individual problem below. Thread repurposed for general discussion about whether to use enums in the code (at the moment we do, but we've identified problems with them which at the moment don't have a satisfactory resolution)

---

Simple problem this, but documented here. In the enum variable spec_mod_type in the plasma structure, declared thus:

``` C
 enum spec_mod_type_enum 
    {   
       SPEC_MOD_PL=1, 
       SPEC_MOD_EXP=2
    } spec_mod_type[NXBANDS];   
```

There is no option for failure. This means that when no model is found in a band, the code tries to do this

``` C
xplasma->spec_mod_type[n] = -1
```

which doesn't work, and the variable is left uninitialised because the variable -1 is not allowed. This is exactly what enums are supposed to iron out, but it's compiler sensitive- my compiler threw no warning here.

then later on, we ask if the variable is >0 to decide if there's a model there, and it is because it is some uninitialised garbage like 35655445, meaning we pass qromb a load of nonsense parameters and get lots of errors.

I've fixed this individual problem but this issue stays open until I've checked that this doesn't happen with other things (which it almost certainly does). This needs some robust checking and we need to be ensured against new variables doing similar things in future.

**Comment by smangham** [comment] 2015-08-05 16:43
This is particularly odd as enums are ints in memory- per standard, you can just set them to values, even if there's no corresponding enum key.

**Comment by Higginbottom** [comment] 2015-08-06 07:06
I'll piggy back on this, because it also seems to be an enum issue. When I compile the latest dev, I get this error. 

python.c:1805:24: warning: comparison of constant 10 with expression of type
      'enum origin_enum' is always true
      [-Wtautological-constant-out-of-range-compare]
      if (p[nn].origin < 10 && (p[nn].freq < freqmin || freqmax < p[nn].freq))

I don't know what this will do, but since all of our compilers seem to throw different errors, I thought I'd let you know what mine says!!

N

**Comment by jhmatthews** [comment] 2015-08-06 08:41
@Higginbottom that's useful- can you let us know compiler version? We need to try and find compiler flags which catch things like that every time so certain compilers don't ignore.

**Comment by Higginbottom** [comment] 2015-08-06 08:46
Well, when I execute make, i get this reported

Compiling with mpicc wrapper, for compiler /usr/bin/clang 4.2.1

I assume you've noticed that the compiler on enginn throws up tons of warnings.....

I've noticed a few more warniings on my version...

Just about ready to submit a pull request for my auger work....

macro_gov.c:117:23: warning: comparison of constant 10 with expression of type 'enum origin_enum' is always true
      [-Wtautological-constant-out-of-range-compare]
                      if (p->origin < 10)
                          ~~~~~~~~~ ^ ~~
macro_gov.c:154:23: warning: comparison of constant 10 with expression of type 'enum origin_enum' is always true
      [-Wtautological-constant-out-of-range-compare]
                      if (p->origin < 10)
                          ~~~~~~~~~ ^ ~~
macro_gov.c:203:17: warning: comparison of constant 10 with expression of type 'enum origin_enum' is always true
      [-Wtautological-constant-out-of-range-compare]
  if (p->origin < 10)

**Comment by jhmatthews** [comment] 2015-08-06 08:58
So the problem we have is that using enums is good if we have those warnings, because it is more robust than using define statements- but if you don't have those warnings, which I didn't because I was using an older compiler, then bad things can happen.

**Comment by smangham** [comment] 2015-08-06 13:21
I posted on StackOverflow and got a response: https://stackoverflow.com/questions/31855252/c-enum-warnings
It looks most likely that because the list of #define statements I converted only had +ive entries, the compiler chose a unsigned int for the enum rather than an int. Adding a -1 key to the enum would fix that.

The `p->origin` warnings arise because again I converted a #define list with 9 entries, but matom_gov adds 10 to whatever the current origin is to reflect that it's been altered by a matom. That list needs to be expanded to include _matom versions of all the origins (or a 'modified by matom' flag needs adding to the photon type?).

In a way, these issues both underscore the need for enums- the full definitions of `spec_mod_type` and `origin` are currently spread across multiple files, with python.h giving a truncated one. Apparently compiling in c++ will give more extensive warnings for enum behaviours, which I'll have to test out.

**Comment by kslong** [comment] 2015-08-14 06:47
My opinion after having worked with the code this week is that enums should be removed from the code unless the can be made to work better.  If not we should go back to #define statements.  The problem is they have to be handled specially with a collection of case statements after a rdpar command is  excecuted, and there is no way I know of to list the possible enums.  

If we are going to keep them we should (a) move them out of the structure definitions to a separate place in the parameter file.  And we should write a routine to parse the enums that can follow each rdpar command. 

The way to do this is not to assign numbers to the enums.  In this case the enums are assigned by default from 0, 1, 2 ..., and you can add a last variable NumEnum or something in the list that you can use to tell you the number of enums.  Then you can search with a for loop, rather than having to write case statements.  

We should also make a convention to define the enums, something with a common start, eg  WINDMODE_whatever so we can find what enum something refers to.  

Also, if we are going to use enums then we should make sure that everything that should be enum'd is enum'd.  

My preference though is to remove them as a good experiment, but not something that really helped us.

**Comment by smangham** [comment] 2015-08-18 12:28
I think that moving the definitions, and switching how rdpar handles these inputs to case statements is a good idea even without enums (so it's easier to switch from numbers in the input file to 'AGN' or 'CV'). Currently input files are quite opaque and difficult to construct (I recently tried converting a non-atom model to matom one, for example, and it wasn't easy). For public release (and potentially public development) making the code more explicit, even at the expense of slightly increasing the length, would be a good tradeoff, particularly as we have a comparatively small number of enum-style inputs.

I definitely agree that they don't help from a technical perspective- it seems the main compiler checks for enums aren't included in c, only c++. I looked into compiling in c++ but the code heavily uses c-only features.

**Comment by jhmatthews** [comment] 2015-09-24 12:48
I solved the original particular issue. The discussion about whether or not to use enums (which has not been resolved to my knowledge) can continue here, meaning I'm closing the original enums proposal (#148) and renaming this issue report.

**Comment by kslong** [comment] 2015-09-24 18:57
I have been gradually eliminating enums in the domain2 version of python.   They would not be hard to put back if we want them.  

One thing I did note however was that ddd or rather gdb at least on linux reports the enum directly and not as an integer, which I thought was nice.  

Anyway, I would like us to decide, up or down.  So could everyone vote!

**Comment by kslong** [comment] 2016-06-01 15:20
Still need to continue with this effort

**Comment by kslong** [comment] 2016-07-01 23:56
I've decided my whole push on removing enums is silly, and am going to close the issue.  Even though enums are not as useful in c as in c++, where an enum outside the allowed set gives an error, they are just as useful as using #define statements.  One can argue that in some ways specifying an enum, really is easier to read than a bunch of #define statements.

The main thing we should agree on is that the variables inside an enum or in a #define statement, especially in python.h, should be CAPITALIZED so that we know that this is a global variable, and that we will continue to weed out places in the code where we have statements like:

if (zdom[ndom].wind_type == 1

@smangham I apologize for being so rigid on this previously.

**Closed as completed by kslong** 2016-07-01 23:56 UTC
Labels: bug, medium
